// Domain 3 — Design High-Performing Architectures (24%)
// Question shape is documented in plan/01-architecture.md.
export const questions = [
  {
    id: "saa-d3-001",
    section: "d3-high-performing",
    subtopic: "ebs-basics",
    type: "single",
    prompt:
      "A database on EC2 needs consistent high IOPS for a transactional workload at the lowest cost that still meets performance. Which Amazon EBS volume type is the BEST default choice?",
    options: [
      { id: "a", text: "gp3 (General Purpose SSD)" },
      { id: "b", text: "sc1 (Cold HDD)" },
      { id: "c", text: "st1 (Throughput Optimized HDD)" },
      { id: "d", text: "standard (previous-generation magnetic)" },
    ],
    correct: ["a"],
    explanation:
      "gp3 SSD delivers a strong baseline of IOPS and throughput that can be provisioned independently, at lower cost than io2, and suits most transactional workloads. HDD types (sc1, st1) are for throughput/sequential or cold data, not high IOPS.",
    difficulty: "medium",
    services: ["ebs", "ec2"],
  },
  {
    id: "saa-d3-002",
    section: "d3-high-performing",
    subtopic: "elasticache",
    type: "single",
    prompt:
      "A read-heavy application repeatedly runs the same expensive queries against an RDS database, causing high latency. Which addition will MOST improve read performance with the least application change?",
    options: [
      { id: "a", text: "Add an in-memory cache such as Amazon ElastiCache in front of the database" },
      { id: "b", text: "Move the database to a larger EBS volume" },
      { id: "c", text: "Enable Multi-AZ on the database" },
      { id: "d", text: "Switch the database to magnetic storage" },
    ],
    correct: ["a"],
    explanation:
      "ElastiCache serves frequently requested results from memory, dramatically lowering read latency and offloading the database. Multi-AZ improves availability, not read performance; larger/slower storage does not address repeated query cost.",
    difficulty: "easy",
    services: ["elasticache", "rds"],
  },
  {
    id: "saa-d3-003",
    section: "d3-high-performing",
    subtopic: "cloudfront",
    type: "single",
    prompt:
      "A global audience downloads large static assets (images, videos) from an S3 bucket, and users far from the bucket Region experience high latency. What should the architect add?",
    options: [
      { id: "a", text: "Amazon CloudFront in front of the S3 bucket" },
      { id: "b", text: "An Application Load Balancer in front of S3" },
      { id: "c", text: "Cross-Region read replicas of S3" },
      { id: "d", text: "A larger S3 storage class" },
    ],
    correct: ["a"],
    explanation:
      "CloudFront caches static content at edge locations close to users, reducing latency and origin load. ALB does not front S3; S3 has no read replicas; storage class does not affect delivery latency.",
    difficulty: "easy",
    services: ["cloudfront", "s3"],
  },
  {
    id: "saa-d3-004",
    section: "d3-high-performing",
    subtopic: "efs",
    type: "single",
    prompt:
      "Several EC2 instances across multiple AZs must read and write the same set of files concurrently with a shared POSIX file system. Which storage service fits?",
    options: [
      { id: "a", text: "Amazon EBS attached to each instance" },
      { id: "b", text: "Amazon EFS mounted by all instances" },
      { id: "c", text: "Amazon S3 mounted as a block device" },
      { id: "d", text: "EC2 instance store volumes" },
    ],
    correct: ["b"],
    explanation:
      "Amazon EFS is a shared, elastic NFS file system that many instances across AZs can mount simultaneously. A standard EBS volume attaches to one instance at a time; S3 is object storage (not a POSIX file system); instance store is ephemeral and local.",
    difficulty: "medium",
    services: ["efs", "ebs", "s3"],
  },
  {
    id: "saa-d3-005",
    section: "d3-high-performing",
    subtopic: "rds-basics",
    type: "single",
    prompt:
      "An application's reporting feature runs many read-only analytical queries that slow down the primary RDS instance handling live traffic. What is the most appropriate way to scale reads?",
    options: [
      { id: "a", text: "Create one or more RDS read replicas and direct reporting queries to them" },
      { id: "b", text: "Enable Multi-AZ on the primary" },
      { id: "c", text: "Increase the backup retention period" },
      { id: "d", text: "Move the primary to a different AZ" },
    ],
    correct: ["a"],
    explanation:
      "Read replicas offload read traffic from the primary, scaling read capacity. Multi-AZ is for failover/availability and its standby does not serve reads; backups and AZ placement do not scale reads.",
    difficulty: "medium",
    services: ["rds"],
  },
  {
    id: "saa-d3-006",
    section: "d3-high-performing",
    subtopic: "global-accelerator",
    type: "single",
    prompt:
      "A TCP-based gaming application needs the lowest possible global network latency and fast regional failover using the AWS global network, with static anycast IP addresses. Which service is the BEST fit?",
    options: [
      { id: "a", text: "Amazon CloudFront" },
      { id: "b", text: "AWS Global Accelerator" },
      { id: "c", text: "Amazon Route 53 latency routing" },
      { id: "d", text: "Amazon API Gateway" },
    ],
    correct: ["b"],
    explanation:
      "Global Accelerator provides static anycast IPs and routes non-HTTP/TCP-UDP traffic over the AWS backbone with fast failover, ideal for latency-sensitive, non-cacheable applications like gaming. CloudFront is optimized for cacheable HTTP content.",
    difficulty: "hard",
    services: ["global-accelerator", "cloudfront"],
  },
  {
    id: "saa-d3-007",
    section: "d3-high-performing",
    subtopic: "rds-basics",
    type: "multi",
    prompt:
      "A relational database is struggling to keep up with growing read traffic. Which TWO changes specifically improve read performance? (Select TWO.)",
    options: [
      { id: "a", text: "Add a caching layer such as ElastiCache or DAX for hot reads" },
      { id: "b", text: "Add read replicas and route read queries to them" },
      { id: "c", text: "Increase the automated backup frequency" },
      { id: "d", text: "Enable Multi-AZ standby for failover" },
      { id: "e", text: "Shorten the maintenance window" },
    ],
    correct: ["a", "b"],
    explanation:
      "Caching frequently read data and adding read replicas both increase read throughput and lower latency. Backups, Multi-AZ failover, and maintenance windows address durability/availability/operations, not read scaling.",
    difficulty: "medium",
    services: ["elasticache", "rds", "dynamodb-dax"],
  },
  {
    id: "saa-d3-008",
    section: "d3-high-performing",
    subtopic: "kinesis",
    type: "single",
    prompt:
      "A company must ingest high-volume clickstream data in real time and allow multiple consumers to process the same stream for analytics. Which service is purpose-built for this?",
    options: [
      { id: "a", text: "Amazon Kinesis Data Streams" },
      { id: "b", text: "Amazon SQS standard queue" },
      { id: "c", text: "Amazon S3 with event notifications" },
      { id: "d", text: "AWS Glue" },
    ],
    correct: ["a"],
    explanation:
      "Kinesis Data Streams is designed for real-time streaming ingestion with multiple independent consumers reading the same data. SQS is for decoupled point-to-point processing (a message is consumed once), S3 is storage, and Glue is batch ETL.",
    difficulty: "medium",
    services: ["kinesis"],
  },
  {
    id: "saa-d3-009",
    section: "d3-high-performing",
    subtopic: "ec2-instance-types",
    type: "single",
    prompt:
      "You would like to deploy a High-Performance Computing (HPC) application on EC2 instances. Which EC2 instance type should you choose?",
    options: [
      { id: "a", text: "Storage Optimized" },
      { id: "b", text: "Compute Optimized" },
      { id: "c", text: "Memory Optimized" },
      { id: "d", text: "General Purpose" },
    ],
    correct: ["b"],
    explanation:
      "Compute Optimized instances (C-family) provide high, sustained CPU performance, which suits compute-bound HPC, batch, and media workloads.",
    difficulty: "easy",
    services: ["ec2"],
  },
  {
    id: "saa-d3-010",
    section: "d3-high-performing",
    subtopic: "ec2-instance-types",
    type: "single",
    prompt:
      "Which EC2 Instance Type should you choose for a critical application that uses an in-memory database?",
    options: [
      { id: "a", text: "Compute Optimized" },
      { id: "b", text: "Storage Optimized" },
      { id: "c", text: "Memory Optimized" },
      { id: "d", text: "General Purpose" },
    ],
    correct: ["c"],
    explanation:
      "Memory Optimized instances (R/X families) provide large, fast RAM for in-memory databases and big in-memory datasets.",
    difficulty: "easy",
    services: ["ec2"],
  },
  {
    id: "saa-d3-011",
    section: "d3-high-performing",
    subtopic: "ec2-instance-types",
    type: "single",
    prompt:
      "You are migrating an on-premises e-commerce OLTP database that handles thousands of requests per second to an EC2 instance. Which EC2 Instance Type should you choose to handle this high-frequency OLTP database?",
    options: [
      { id: "a", text: "Compute Optimized" },
      { id: "b", text: "Storage Optimized" },
      { id: "c", text: "Memory Optimized" },
      { id: "d", text: "General Purpose" },
    ],
    correct: ["c"],
    explanation:
      "High-frequency OLTP databases benefit from Memory Optimized instances, which keep large working sets in RAM for fast, high-throughput transaction processing.",
    difficulty: "medium",
    services: ["ec2"],
  },
  {
    id: "saa-d3-012",
    section: "d3-high-performing",
    subtopic: "ec2-placement",
    type: "single",
    prompt:
      "You have an application performing big data analysis on a fleet of EC2 instances and want the highest networking performance while they communicate with each other. Which EC2 Placement Group should you choose?",
    options: [
      { id: "a", text: "Spread Placement Group" },
      { id: "b", text: "Cluster Placement Group" },
      { id: "c", text: "Partition Placement Group" },
    ],
    correct: ["b"],
    explanation:
      "A cluster placement group packs instances close together within a single AZ to achieve the highest network throughput and lowest latency between them.",
    difficulty: "medium",
    services: ["ec2", "placement-groups"],
  },
  {
    id: "saa-d3-013",
    section: "d3-high-performing",
    subtopic: "ebs-basics",
    type: "single",
    prompt:
      "You terminated an EC2 instance in us-east-1a and its attached EBS volume is now available. A teammate tries to attach it to an instance in us-east-1b but can't. What is a possible cause?",
    options: [
      { id: "a", text: "He's missing IAM permissions" },
      { id: "b", text: "EBS volumes are locked to an AWS Region" },
      { id: "c", text: "EBS volumes are locked to an Availability Zone" },
    ],
    correct: ["c"],
    explanation:
      "An EBS volume exists in a single Availability Zone and can only attach to instances in that same AZ. To move it, create a snapshot and restore it in the target AZ.",
    difficulty: "medium",
    services: ["ebs"],
  },
  {
    id: "saa-d3-014",
    section: "d3-high-performing",
    subtopic: "ebs-basics",
    type: "single",
    prompt:
      "You launched an EC2 instance with two EBS volumes: the root volume and an additional volume for data. Later you terminate the instance. What is the default behavior for each EBS volume?",
    options: [
      { id: "a", text: "Both the root volume and the additional EBS volume will be deleted" },
      { id: "b", text: "The root volume will be deleted and the additional EBS volume will not be deleted" },
      { id: "c", text: "The root volume will not be deleted and the additional EBS volume will be deleted" },
      { id: "d", text: "Both the root volume and the additional EBS volume will not be deleted" },
    ],
    correct: ["b"],
    explanation:
      "By default the root volume has DeleteOnTermination = true, while additional attached EBS volumes default to false, so they persist after the instance is terminated.",
    difficulty: "medium",
    services: ["ebs", "ec2"],
  },
  {
    id: "saa-d3-015",
    section: "d3-high-performing",
    subtopic: "ami",
    type: "single",
    prompt:
      "You can use an AMI in the N. Virginia Region (us-east-1) to launch an EC2 instance in any AWS Region.",
    options: [
      { id: "a", text: "True" },
      { id: "b", text: "False" },
    ],
    correct: ["b"],
    explanation:
      "AMIs are Region-scoped. To launch from that AMI in another Region, you must first copy the AMI to the target Region.",
    difficulty: "easy",
    services: ["ec2", "ami"],
  },
  {
    id: "saa-d3-016",
    section: "d3-high-performing",
    subtopic: "ebs-basics",
    type: "single",
    prompt:
      "Which of the following sets of EBS volume types can be used as boot volumes when you create EC2 instances?",
    options: [
      { id: "a", text: "gp2, gp3, st1, sc1" },
      { id: "b", text: "gp2, gp3, io1, io2" },
      { id: "c", text: "io1, io2, st1, sc1" },
    ],
    correct: ["b"],
    explanation:
      "SSD-backed volumes (gp2, gp3, io1, io2) can be used as boot volumes. HDD types (st1, sc1) cannot be boot volumes.",
    difficulty: "medium",
    services: ["ebs"],
  },
  {
    id: "saa-d3-017",
    section: "d3-high-performing",
    subtopic: "ebs-basics",
    type: "single",
    prompt: "What is EBS Multi-Attach?",
    options: [
      { id: "a", text: "Attach the same EBS volume to multiple EC2 instances in multiple AZs" },
      { id: "b", text: "Attach multiple EBS volumes in the same AZ to the same EC2 instance" },
      { id: "c", text: "Attach the same EBS volume to multiple EC2 instances in the same AZ" },
      { id: "d", text: "Attach multiple EBS volumes in multiple AZs to the same EC2 instance" },
    ],
    correct: ["c"],
    explanation:
      "EBS Multi-Attach lets a single Provisioned IOPS (io1/io2) volume be attached to multiple EC2 instances within the same Availability Zone.",
    difficulty: "medium",
    services: ["ebs"],
  },
  {
    id: "saa-d3-018",
    section: "d3-high-performing",
    subtopic: "efs",
    type: "single",
    prompt:
      "You have a fleet of EC2 instances distributed across AZs that process a large data set. How do you make the same data accessible as an NFS drive to all of your EC2 instances?",
    options: [
      { id: "a", text: "Use EBS" },
      { id: "b", text: "Use EFS" },
      { id: "c", text: "Use an Instance Store" },
    ],
    correct: ["b"],
    explanation:
      "Amazon EFS is a managed NFS file system that many instances across multiple AZs can mount and share concurrently.",
    difficulty: "easy",
    services: ["efs"],
  },
  {
    id: "saa-d3-019",
    section: "d3-high-performing",
    subtopic: "instance-store",
    type: "single",
    prompt:
      "You want a high-performance local cache for an application on an EC2 instance and don't mind losing the cache when the instance is terminated. Which storage mechanism do you recommend?",
    options: [
      { id: "a", text: "EBS" },
      { id: "b", text: "EFS" },
      { id: "c", text: "Instance Store" },
    ],
    correct: ["c"],
    explanation:
      "Instance store provides high-performance ephemeral storage physically attached to the host — ideal for a cache you can afford to lose when the instance stops or terminates.",
    difficulty: "medium",
    services: ["instance-store", "ec2"],
  },
  {
    id: "saa-d3-020",
    section: "d3-high-performing",
    subtopic: "ebs-basics",
    type: "single",
    prompt:
      "You are running a high-performance database that requires very high IOPS (around 310,000) for its underlying storage. What do you recommend?",
    options: [
      { id: "a", text: "Use an EBS gp2 drive" },
      { id: "b", text: "Use an EBS io1 drive" },
      { id: "c", text: "Use an EC2 Instance Store" },
      { id: "d", text: "Use an EBS io2 Block Express drive" },
    ],
    correct: ["d"],
    explanation:
      "io2 Block Express delivers the highest EBS performance (very high IOPS and throughput with sub-millisecond latency), making it the right EBS choice for extreme-IOPS databases.",
    difficulty: "hard",
    services: ["ebs"],
  },
  {
    id: "saa-d3-021",
    section: "d3-high-performing",
    subtopic: "ec2-basics",
    type: "single",
    prompt: "How is Amazon EC2 best described?",
    options: [
      { id: "a", text: "A service that provides resizable virtual servers (compute capacity) in the cloud" },
      { id: "b", text: "An object storage service" },
      { id: "c", text: "A managed relational database" },
      { id: "d", text: "A content delivery network" },
    ],
    correct: ["a"],
    explanation:
      "EC2 (Elastic Compute Cloud) provides on-demand, resizable virtual machines. S3 is object storage, RDS is managed databases, and CloudFront is the CDN.",
    difficulty: "easy",
    services: ["ec2"],
  },
  {
    id: "saa-d3-022",
    section: "d3-high-performing",
    subtopic: "ec2-basics",
    type: "single",
    prompt: "What is an Amazon Machine Image (AMI)?",
    options: [
      { id: "a", text: "A template (OS, software, and configuration) used to launch EC2 instances" },
      { id: "b", text: "A type of EBS volume" },
      { id: "c", text: "A VPC networking component" },
      { id: "d", text: "An EC2 billing plan" },
    ],
    correct: ["a"],
    explanation:
      "An AMI is the image/template an instance boots from — it bundles the OS, pre-installed software, and configuration. AMIs are Region-scoped.",
    difficulty: "easy",
    services: ["ec2", "ami"],
  },
  {
    id: "saa-d3-023",
    section: "d3-high-performing",
    subtopic: "ec2-basics",
    type: "single",
    prompt: "An EC2 User Data script runs:",
    options: [
      { id: "a", text: "Once, at the instance's first boot, with root privileges" },
      { id: "b", text: "Every time a user logs in" },
      { id: "c", text: "Only when you manually SSH into the instance" },
      { id: "d", text: "Never automatically; AWS Support runs it" },
    ],
    correct: ["a"],
    explanation:
      "User Data is a bootstrap script executed once at first launch as root, used to install software and configure the instance automatically.",
    difficulty: "easy",
    services: ["ec2"],
  },
  {
    id: "saa-d3-024",
    section: "d3-high-performing",
    subtopic: "ec2-basics",
    type: "single",
    prompt:
      "What happens to the data on the root EBS volume when you STOP (not terminate) an EC2 instance?",
    options: [
      { id: "a", text: "It is preserved, and the instance can be started again later" },
      { id: "b", text: "It is deleted immediately" },
      { id: "c", text: "It is automatically moved to S3" },
      { id: "d", text: "It is wiped and re-encrypted" },
    ],
    correct: ["a"],
    explanation:
      "Stopping keeps the EBS-backed root volume and its data; you can start the instance again. Terminating deletes the root volume by default (DeleteOnTermination = true).",
    difficulty: "medium",
    services: ["ec2", "ebs"],
  },
  {
    id: "saa-d3-025",
    section: "d3-high-performing",
    subtopic: "ec2-instance-types",
    type: "single",
    prompt: "In the instance type m5.large, what does the leading 'm' indicate?",
    options: [
      { id: "a", text: "The instance family/category (here, general purpose)" },
      { id: "b", text: "The number of vCPUs" },
      { id: "c", text: "The AWS Region" },
      { id: "d", text: "The amount of attached storage" },
    ],
    correct: ["a"],
    explanation:
      "The letter is the family (m = general purpose, c = compute optimized, r = memory optimized, etc.); the number is the generation, and the suffix (large, xlarge) is the size.",
    difficulty: "medium",
    services: ["ec2"],
  },
  {
    id: "saa-d3-026",
    section: "d3-high-performing",
    subtopic: "ec2-instance-types",
    type: "single",
    prompt:
      "Which EC2 instance family is the balanced, general-purpose default for typical web and application servers?",
    options: [
      { id: "a", text: "General Purpose (e.g., T and M families)" },
      { id: "b", text: "Compute Optimized" },
      { id: "c", text: "Memory Optimized" },
      { id: "d", text: "Storage Optimized" },
    ],
    correct: ["a"],
    explanation:
      "General Purpose instances balance CPU, memory, and networking — a sensible default. Specialized families are chosen when a workload is clearly CPU-, memory-, or storage-bound.",
    difficulty: "easy",
    services: ["ec2"],
  },
  {
    id: "saa-d3-027",
    section: "d3-high-performing",
    subtopic: "ec2-placement",
    type: "single",
    prompt:
      "Which EC2 placement group strategy spreads instances across partitions (groups of racks) and is designed for large distributed/replicated workloads like HDFS, HBase, and Cassandra?",
    options: [
      { id: "a", text: "Partition" },
      { id: "b", text: "Cluster" },
      { id: "c", text: "Spread" },
      { id: "d", text: "Default (no placement group)" },
    ],
    correct: ["a"],
    explanation:
      "Partition placement groups isolate instances into partitions on separate racks, so a hardware failure affects only one partition — ideal for large distributed data systems.",
    difficulty: "medium",
    services: ["ec2", "placement-groups"],
  },
  {
    id: "saa-d3-028",
    section: "d3-high-performing",
    subtopic: "ec2-placement",
    type: "single",
    prompt: "What is a key tradeoff of a Cluster placement group?",
    options: [
      { id: "a", text: "It gives very low latency / high throughput, but packs instances in a single AZ, so an AZ failure can affect all of them" },
      { id: "b", text: "It automatically spans every AWS Region" },
      { id: "c", text: "It prevents the use of enhanced networking" },
      { id: "d", text: "It allows only one instance" },
    ],
    correct: ["a"],
    explanation:
      "Cluster groups co-locate instances for maximum network performance, but because they're in one AZ they don't protect against an AZ-level failure.",
    difficulty: "medium",
    services: ["ec2", "placement-groups"],
  },
  {
    id: "saa-d3-029",
    section: "d3-high-performing",
    subtopic: "ec2-placement",
    type: "single",
    prompt: "A Spread placement group is best suited for which scenario?",
    options: [
      { id: "a", text: "A small number of critical instances that must sit on distinct hardware to avoid simultaneous failure" },
      { id: "b", text: "Maximizing inter-node network throughput for HPC" },
      { id: "c", text: "Packing thousands of instances onto one rack" },
      { id: "d", text: "Reducing per-hour instance cost" },
    ],
    correct: ["a"],
    explanation:
      "Spread groups place each instance on distinct racks (limited number per AZ), maximizing isolation for a few critical instances. Cluster is for throughput; placement groups don't change pricing.",
    difficulty: "medium",
    services: ["ec2", "placement-groups"],
  },
  {
    id: "saa-d3-030",
    section: "d3-high-performing",
    subtopic: "ebs-snapshots",
    type: "single",
    prompt: "What is an EBS snapshot?",
    options: [
      { id: "a", text: "A point-in-time backup of an EBS volume, stored in Amazon S3 (managed by AWS)" },
      { id: "b", text: "A copy of an AMI" },
      { id: "c", text: "A dump of the instance's RAM" },
      { id: "d", text: "A backup of a security group's rules" },
    ],
    correct: ["a"],
    explanation:
      "Snapshots are incremental point-in-time backups of EBS volumes stored durably in S3 (you don't manage the bucket). They can be copied across Regions and used to create new volumes.",
    difficulty: "easy",
    services: ["ebs"],
  },
  {
    id: "saa-d3-031",
    section: "d3-high-performing",
    subtopic: "ebs-snapshots",
    type: "single",
    prompt:
      "How do you move an EBS volume's data to a different Availability Zone (or Region)?",
    options: [
      { id: "a", text: "Create a snapshot, then create a volume from it in the target AZ (copy the snapshot to another Region first if needed)" },
      { id: "b", text: "Detach the volume and reattach it directly in the other AZ" },
      { id: "c", text: "EBS volumes automatically replicate to every AZ" },
      { id: "d", text: "Enable Multi-Attach across AZs" },
    ],
    correct: ["a"],
    explanation:
      "Because a volume is AZ-bound, you snapshot it and restore into the target AZ; to change Region you copy the snapshot to that Region first.",
    difficulty: "medium",
    services: ["ebs"],
  },
  {
    id: "saa-d3-032",
    section: "d3-high-performing",
    subtopic: "ami",
    type: "single",
    prompt: "How do you create a custom AMI?",
    options: [
      { id: "a", text: "From a configured EC2 instance (AWS snapshots its volumes into the AMI)" },
      { id: "b", text: "From an S3 bucket policy" },
      { id: "c", text: "From an Elastic IP allocation" },
      { id: "d", text: "From a security group export" },
    ],
    correct: ["a"],
    explanation:
      "You build a custom AMI from an instance you've configured; AWS captures the volumes as snapshots that the AMI references, so new instances launch pre-configured.",
    difficulty: "easy",
    services: ["ec2", "ami"],
  },
  {
    id: "saa-d3-033",
    section: "d3-high-performing",
    subtopic: "ami",
    type: "single",
    prompt:
      "You need to launch instances from your custom AMI in another Region. What must you do?",
    options: [
      { id: "a", text: "Copy the AMI to the target Region first" },
      { id: "b", text: "Nothing — AMIs are global" },
      { id: "c", text: "Recreate every instance manually in that Region" },
      { id: "d", text: "Enable Multi-Attach on the AMI" },
    ],
    correct: ["a"],
    explanation:
      "AMIs are Region-scoped. Copy the AMI (and its backing snapshots) to the destination Region before launching there.",
    difficulty: "medium",
    services: ["ec2", "ami"],
  },
  {
    id: "saa-d3-034",
    section: "d3-high-performing",
    subtopic: "ami",
    type: "single",
    prompt:
      "Why bake software into a custom (\"golden\") AMI instead of installing it via User Data on every launch?",
    options: [
      { id: "a", text: "Faster, more consistent launches since software is pre-installed in the image" },
      { id: "b", text: "It is required by AWS for all instances" },
      { id: "c", text: "It eliminates all EBS storage costs" },
      { id: "d", text: "It disables security groups" },
    ],
    correct: ["a"],
    explanation:
      "A golden AMI reduces boot time and configuration drift because the software is already present, versus running a bootstrap script each launch.",
    difficulty: "medium",
    services: ["ec2", "ami"],
  },
  {
    id: "saa-d3-035",
    section: "d3-high-performing",
    subtopic: "ami",
    type: "single",
    prompt: "What does an AMI include?",
    options: [
      { id: "a", text: "The OS, configuration, and (via snapshots) the EBS volume data needed to boot an instance" },
      { id: "b", text: "Only the instance type" },
      { id: "c", text: "Only the security groups" },
      { id: "d", text: "Only an Elastic IP" },
    ],
    correct: ["a"],
    explanation:
      "An AMI bundles the root volume template (OS + software + settings) plus block-device mappings/snapshots, so launched instances are ready to run.",
    difficulty: "easy",
    services: ["ec2", "ami"],
  },
  {
    id: "saa-d3-036",
    section: "d3-high-performing",
    subtopic: "instance-store",
    type: "single",
    prompt:
      "What happens to data on an EC2 Instance Store volume when the instance is stopped or terminated?",
    options: [
      { id: "a", text: "It is lost — instance store is ephemeral, physically attached to the host" },
      { id: "b", text: "It persists like an EBS volume" },
      { id: "c", text: "It is automatically copied to S3" },
      { id: "d", text: "It is snapshotted automatically" },
    ],
    correct: ["a"],
    explanation:
      "Instance store is ephemeral local disk; its data is lost when the instance stops or terminates (and on host failure). Use EBS for persistence.",
    difficulty: "easy",
    services: ["instance-store"],
  },
  {
    id: "saa-d3-037",
    section: "d3-high-performing",
    subtopic: "instance-store",
    type: "single",
    prompt: "Why might you choose an Instance Store volume over EBS?",
    options: [
      { id: "a", text: "Very high IOPS/throughput from physically attached disks, for ephemeral data" },
      { id: "b", text: "Because it provides durable long-term storage" },
      { id: "c", text: "Because it can be detached and reattached to other instances" },
      { id: "d", text: "Because it is always free" },
    ],
    correct: ["a"],
    explanation:
      "Instance store offers extremely high local disk performance, ideal for caches, buffers, and scratch data you can afford to lose.",
    difficulty: "medium",
    services: ["instance-store"],
  },
  {
    id: "saa-d3-038",
    section: "d3-high-performing",
    subtopic: "instance-store",
    type: "single",
    prompt: "Which statement about Instance Store vs EBS is true?",
    options: [
      { id: "a", text: "EBS persists independently of the instance; Instance Store is tied to the host and lost on stop/terminate" },
      { id: "b", text: "Both persist after termination" },
      { id: "c", text: "Instance Store can be Multi-Attached across AZs" },
      { id: "d", text: "EBS is ephemeral and Instance Store is durable" },
    ],
    correct: ["a"],
    explanation:
      "EBS is network-attached, durable, and survives instance stop/terminate; instance store is local and ephemeral.",
    difficulty: "medium",
    services: ["instance-store", "ebs"],
  },
  {
    id: "saa-d3-039",
    section: "d3-high-performing",
    subtopic: "instance-store",
    type: "single",
    prompt: "Which workload is the best fit for an Instance Store volume?",
    options: [
      { id: "a", text: "A high-speed temporary cache or scratch space that can be regenerated" },
      { id: "b", text: "A primary database that must not lose data" },
      { id: "c", text: "Long-term backups" },
      { id: "d", text: "Files shared across many instances" },
    ],
    correct: ["a"],
    explanation:
      "Ephemeral, high-performance local storage suits regenerable scratch/cache data. Durable or shared needs call for EBS or EFS.",
    difficulty: "easy",
    services: ["instance-store"],
  },
  {
    id: "saa-d3-040",
    section: "d3-high-performing",
    subtopic: "efs",
    type: "single",
    prompt: "How does Amazon EFS handle storage capacity?",
    options: [
      { id: "a", text: "It is elastic — it grows and shrinks automatically as files are added and removed" },
      { id: "b", text: "You must pre-provision a fixed size" },
      { id: "c", text: "It is capped at 16 TiB" },
      { id: "d", text: "It requires manual resizing commands" },
    ],
    correct: ["a"],
    explanation:
      "EFS automatically scales capacity up and down and you pay for what you use — no provisioning required.",
    difficulty: "easy",
    services: ["efs"],
  },
  {
    id: "saa-d3-041",
    section: "d3-high-performing",
    subtopic: "efs",
    type: "single",
    prompt: "Which compute can mount an Amazon EFS file system?",
    options: [
      { id: "a", text: "Many Linux instances across multiple AZs, concurrently, over NFS" },
      { id: "b", text: "Only a single Windows instance" },
      { id: "c", text: "Only AWS Lambda" },
      { id: "d", text: "Only one instance at a time" },
    ],
    correct: ["a"],
    explanation:
      "EFS is a managed NFS file system for Linux that many instances across AZs can mount at once. For Windows file shares, use Amazon FSx instead.",
    difficulty: "medium",
    services: ["efs"],
  },
  {
    id: "saa-d3-042",
    section: "d3-high-performing",
    subtopic: "efs",
    type: "single",
    prompt: "What is the key difference between Amazon EFS and Amazon EBS?",
    options: [
      { id: "a", text: "EFS is a shared file system many instances across AZs can mount; EBS is a block volume attached to one instance in one AZ" },
      { id: "b", text: "EFS is block storage and EBS is object storage" },
      { id: "c", text: "EBS is a shared file system and EFS is single-attach" },
      { id: "d", text: "They are functionally identical" },
    ],
    correct: ["a"],
    explanation:
      "EFS = shared, multi-AZ, multi-instance file storage (NFS). EBS = single-AZ block volume normally attached to one instance.",
    difficulty: "medium",
    services: ["efs", "ebs"],
  },
  {
    id: "saa-d3-043",
    section: "d3-high-performing",
    subtopic: "rds-basics",
    type: "single",
    prompt: "What is Amazon RDS?",
    options: [
      { id: "a", text: "A managed relational database service (patching, backups, failover) for engines like MySQL, PostgreSQL, MariaDB, Oracle, and SQL Server" },
      { id: "b", text: "A NoSQL key-value database" },
      { id: "c", text: "An object storage service" },
      { id: "d", text: "An in-memory cache" },
    ],
    correct: ["a"],
    explanation:
      "RDS runs managed relational databases — AWS handles provisioning, patching, backups, and (with Multi-AZ) failover. DynamoDB is NoSQL, S3 is object storage, ElastiCache is the cache.",
    difficulty: "easy",
    services: ["rds"],
  },
  {
    id: "saa-d3-044",
    section: "d3-high-performing",
    subtopic: "rds-basics",
    type: "single",
    prompt: "Which statement correctly contrasts RDS Read Replicas with Multi-AZ?",
    options: [
      { id: "a", text: "Read Replicas (asynchronous) scale read traffic and can be cross-Region; Multi-AZ keeps a synchronous standby for automatic failover/HA" },
      { id: "b", text: "They are the same feature" },
      { id: "c", text: "Read Replicas provide automatic failover" },
      { id: "d", text: "Multi-AZ is used to scale read traffic" },
    ],
    correct: ["a"],
    explanation:
      "Read Replicas are for read scaling (async, optionally cross-Region). Multi-AZ is for availability — a synchronous standby that fails over automatically and does not serve reads.",
    difficulty: "medium",
    services: ["rds"],
  },
  {
    id: "saa-d3-045",
    section: "d3-high-performing",
    subtopic: "aurora",
    type: "single",
    prompt: "How should an application spread read queries across Aurora Replicas?",
    options: [
      { id: "a", text: "Connect to the Aurora reader endpoint, which load-balances reads across replicas" },
      { id: "b", text: "Always use the writer endpoint for reads" },
      { id: "c", text: "Connect to each replica's IP manually" },
      { id: "d", text: "Aurora cannot scale reads" },
    ],
    correct: ["a"],
    explanation:
      "The reader endpoint automatically balances read connections across available Aurora Replicas; the writer endpoint is for writes (and points to the primary).",
    difficulty: "medium",
    services: ["aurora"],
  },
  {
    id: "saa-d3-046",
    section: "d3-high-performing",
    subtopic: "elasticache",
    type: "single",
    prompt: "What is Amazon ElastiCache?",
    options: [
      { id: "a", text: "A managed in-memory cache service offering Redis and Memcached" },
      { id: "b", text: "A managed relational database" },
      { id: "c", text: "An object storage service" },
      { id: "d", text: "A load balancer" },
    ],
    correct: ["a"],
    explanation:
      "ElastiCache provides managed Redis or Memcached in-memory caches, used to reduce latency and offload backend databases.",
    difficulty: "easy",
    services: ["elasticache"],
  },
  {
    id: "saa-d3-047",
    section: "d3-high-performing",
    subtopic: "elasticache",
    type: "single",
    prompt:
      "A read-heavy app repeatedly runs the same queries against RDS. How does ElastiCache help?",
    options: [
      { id: "a", text: "Cache frequent results in memory to cut database load and latency" },
      { id: "b", text: "Replace the database entirely with no code changes" },
      { id: "c", text: "Encrypt the database automatically" },
      { id: "d", text: "Provide automatic RDS failover" },
    ],
    correct: ["a"],
    explanation:
      "A cache-aside pattern stores hot results in ElastiCache; repeated reads hit memory instead of the database. Your app must manage cache reads/writes/invalidation.",
    difficulty: "easy",
    services: ["elasticache", "rds"],
  },
  {
    id: "saa-d3-048",
    section: "d3-high-performing",
    subtopic: "elasticache",
    type: "single",
    prompt: "Which statement about ElastiCache engines is correct?",
    options: [
      { id: "a", text: "Redis supports replication, persistence, and high availability; Memcached is a simpler multi-threaded cache without persistence" },
      { id: "b", text: "Memcached supports replication and persistence; Redis does not" },
      { id: "c", text: "Redis is non-persistent only" },
      { id: "d", text: "They are identical in capabilities" },
    ],
    correct: ["a"],
    explanation:
      "Redis adds replication, persistence, backups, and failover (HA); Memcached is a simple, multi-threaded, non-persistent cache for pure scaling.",
    difficulty: "medium",
    services: ["elasticache"],
  },
  {
    id: "saa-d3-049",
    section: "d3-high-performing",
    subtopic: "elasticache",
    type: "single",
    prompt: "How can ElastiCache help make a web tier stateless?",
    options: [
      { id: "a", text: "Store user session state in ElastiCache so any instance can serve any request" },
      { id: "b", text: "Pin each user to one instance with sticky sessions only" },
      { id: "c", text: "Store sessions on each instance's local disk" },
      { id: "d", text: "Remove the load balancer" },
    ],
    correct: ["a"],
    explanation:
      "Externalizing session data to ElastiCache lets the app tier be stateless, so instances can scale in/out freely behind a load balancer.",
    difficulty: "medium",
    services: ["elasticache"],
  },
  {
    id: "saa-d3-050",
    section: "d3-high-performing",
    subtopic: "r53-routing",
    type: "single",
    prompt:
      "You want users automatically routed to the AWS Region that gives them the lowest latency. Which Route 53 routing policy?",
    options: [
      { id: "a", text: "Latency-based routing" },
      { id: "b", text: "Weighted routing" },
      { id: "c", text: "Geolocation routing" },
      { id: "d", text: "Simple routing" },
    ],
    correct: ["a"],
    explanation:
      "Latency-based routing sends users to the Region with the lowest measured latency for them. Geolocation routes by location (not necessarily fastest), and weighted splits by ratio.",
    difficulty: "medium",
    services: ["route-53"],
  },
  {
    id: "saa-d3-051",
    section: "d3-high-performing",
    subtopic: "arch-patterns",
    type: "single",
    prompt:
      "An e-commerce app keeps a shopping cart. To scale the web tier statelessly while preserving carts across requests, where should the session/cart state live?",
    options: [
      { id: "a", text: "An external store such as Amazon ElastiCache or DynamoDB" },
      { id: "b", text: "On each instance's local disk" },
      { id: "c", text: "Inside the load balancer" },
      { id: "d", text: "On an instance store volume" },
    ],
    correct: ["a"],
    explanation:
      "Externalizing session/cart state (ElastiCache or DynamoDB) keeps the web tier stateless so any instance can serve any request and instances can scale freely.",
    difficulty: "medium",
    services: ["elasticache", "dynamodb"],
  },
  {
    id: "saa-d3-052",
    section: "d3-high-performing",
    subtopic: "arch-patterns",
    type: "single",
    prompt:
      "A WordPress site runs on multiple EC2 instances that must share the same uploaded media files as a mounted file system. Which storage fits?",
    options: [
      { id: "a", text: "Amazon EFS (a shared file system many instances can mount)" },
      { id: "b", text: "A separate EBS volume attached to each instance" },
      { id: "c", text: "Instance store on each instance" },
      { id: "d", text: "S3 Glacier Deep Archive" },
    ],
    correct: ["a"],
    explanation:
      "EFS provides a shared POSIX file system mountable by many instances across AZs — ideal for shared WordPress uploads. EBS attaches to one instance; instance store is ephemeral.",
    difficulty: "medium",
    services: ["efs"],
  },
  {
    id: "saa-d3-053",
    section: "d3-high-performing",
    subtopic: "s3-basics",
    type: "single",
    prompt: "What is Amazon S3?",
    options: [
      { id: "a", text: "Object storage for files (\"objects\") in buckets, with very high durability and virtually unlimited scale" },
      { id: "b", text: "Block storage attached to a single EC2 instance" },
      { id: "c", text: "A managed relational database" },
      { id: "d", text: "A POSIX file system mounted over NFS" },
    ],
    correct: ["a"],
    explanation:
      "S3 stores objects (key + data + metadata) in buckets. It's object storage — not block (EBS) or file (EFS) storage — and scales virtually without limit.",
    difficulty: "easy",
    services: ["s3"],
  },
  {
    id: "saa-d3-054",
    section: "d3-high-performing",
    subtopic: "s3-basics",
    type: "single",
    prompt: "Which statement about Amazon S3 is correct?",
    options: [
      { id: "a", text: "Objects live in buckets identified by a key, and bucket names are globally unique" },
      { id: "b", text: "S3 stores data as raw disk blocks" },
      { id: "c", text: "Buckets are Availability-Zone-specific volumes" },
      { id: "d", text: "Every object must be smaller than 5 GB" },
    ],
    correct: ["a"],
    explanation:
      "Each object has a key within a globally-unique-named bucket. (Objects can be up to 5 TB; a single PUT is limited to 5 GB, with multipart upload for larger.)",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d3-055",
    section: "d3-high-performing",
    subtopic: "s3-basics",
    type: "single",
    prompt: "What durability does S3 Standard provide?",
    options: [
      { id: "a", text: "11 nines (99.999999999%), storing data redundantly across multiple AZs" },
      { id: "b", text: "A single copy in one AZ" },
      { id: "c", text: "99% durability" },
      { id: "d", text: "No durability guarantee" },
    ],
    correct: ["a"],
    explanation:
      "S3 is designed for 11 nines of durability by redundantly storing objects across multiple devices and Availability Zones.",
    difficulty: "easy",
    services: ["s3"],
  },
  {
    id: "saa-d3-056",
    section: "d3-high-performing",
    subtopic: "s3-basics",
    type: "single",
    prompt: "Can Amazon S3 host a static website?",
    options: [
      { id: "a", text: "Yes — S3 can serve static content (HTML/CSS/JS) directly via static website hosting" },
      { id: "b", text: "No, S3 is only for backups" },
      { id: "c", text: "Only if paired with an EC2 instance" },
      { id: "d", text: "Only through an RDS database" },
    ],
    correct: ["a"],
    explanation:
      "S3 static website hosting serves static assets directly (often fronted by CloudFront for HTTPS and caching).",
    difficulty: "easy",
    services: ["s3"],
  },
  {
    id: "saa-d3-057",
    section: "d3-high-performing",
    subtopic: "s3-basics",
    type: "single",
    prompt: "Which is a typical use case for Amazon S3?",
    options: [
      { id: "a", text: "Backups, data lakes, media files, and static website assets" },
      { id: "b", text: "Running a relational database engine" },
      { id: "c", text: "Hosting a Linux desktop environment" },
      { id: "d", text: "Serving as an EC2 boot volume" },
    ],
    correct: ["a"],
    explanation:
      "S3 is ideal for durable object storage: backups, data lakes, media, logs, and static site content. Boot volumes are EBS; databases are RDS/DynamoDB.",
    difficulty: "easy",
    services: ["s3"],
  },
  {
    id: "saa-d3-058",
    section: "d3-high-performing",
    subtopic: "s3-events-perf",
    type: "single",
    prompt:
      "To speed up uploads of large files to S3 from geographically distant clients, what helps?",
    options: [
      { id: "a", text: "Multipart upload (parallel parts) and S3 Transfer Acceleration (uses the CloudFront edge network)" },
      { id: "b", text: "Switching to a cheaper storage class" },
      { id: "c", text: "Disabling versioning" },
      { id: "d", text: "Routing through a NAT gateway" },
    ],
    correct: ["a"],
    explanation:
      "Multipart upload parallelizes large transfers (and is recommended/required above certain sizes); Transfer Acceleration routes uploads over the AWS edge network for distant clients.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d3-059",
    section: "d3-high-performing",
    subtopic: "s3-events-perf",
    type: "single",
    prompt: "Which statement about S3 request performance is correct?",
    options: [
      { id: "a", text: "S3 scales to very high request rates per prefix; spreading keys across prefixes increases parallel throughput" },
      { id: "b", text: "S3 is limited to one request per second" },
      { id: "c", text: "You must manually pre-warm every bucket" },
      { id: "d", text: "Performance depends only on the bucket's Region" },
    ],
    correct: ["a"],
    explanation:
      "S3 supports thousands of requests/sec per prefix and scales automatically; distributing object keys across prefixes increases aggregate parallel throughput.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d3-060",
    section: "d3-high-performing",
    subtopic: "cloudfront",
    type: "single",
    prompt: "What is Amazon CloudFront?",
    options: [
      { id: "a", text: "A global content delivery network (CDN) that caches content at edge locations for low-latency delivery" },
      { id: "b", text: "A relational database" },
      { id: "c", text: "A load balancer that works within a single AZ" },
      { id: "d", text: "A site-to-site VPN service" },
    ],
    correct: ["a"],
    explanation:
      "CloudFront caches and serves content from edge locations near users, reducing latency and offloading origins (S3, ALB/EC2, or any HTTP server).",
    difficulty: "easy",
    services: ["cloudfront"],
  },
  {
    id: "saa-d3-061",
    section: "d3-high-performing",
    subtopic: "cloudfront",
    type: "single",
    prompt:
      "You updated files at the origin, but CloudFront keeps serving the old cached versions until their TTL expires. How do you force a refresh now?",
    options: [
      { id: "a", text: "Create a CloudFront cache invalidation for the affected paths" },
      { id: "b", text: "Delete and recreate the distribution" },
      { id: "c", text: "Rename the origin bucket" },
      { id: "d", text: "Disable versioning" },
    ],
    correct: ["a"],
    explanation:
      "A cache invalidation tells CloudFront to evict cached objects for given paths so the next request fetches fresh content from the origin (versioned filenames are an alternative).",
    difficulty: "medium",
    services: ["cloudfront"],
  },
  {
    id: "saa-d3-062",
    section: "d3-high-performing",
    subtopic: "global-accelerator",
    type: "single",
    prompt: "What does AWS Global Accelerator provide?",
    options: [
      { id: "a", text: "Two static anycast IPs and routing over the AWS global network to the nearest healthy endpoint, improving performance for TCP/UDP apps" },
      { id: "b", text: "A CDN that caches HTTP content at the edge" },
      { id: "c", text: "A managed relational database" },
      { id: "d", text: "DNS zone hosting" },
    ],
    correct: ["a"],
    explanation:
      "Global Accelerator gives you fixed anycast IPs and routes traffic over the AWS backbone to the optimal healthy endpoint, ideal for non-cacheable TCP/UDP workloads.",
    difficulty: "medium",
    services: ["global-accelerator"],
  },
  {
    id: "saa-d3-063",
    section: "d3-high-performing",
    subtopic: "global-accelerator",
    type: "single",
    prompt: "Which workload benefits most from AWS Global Accelerator?",
    options: [
      { id: "a", text: "A latency-sensitive, non-HTTP TCP/UDP application (e.g., gaming, VoIP) needing fast regional failover and static IPs" },
      { id: "b", text: "A static website with highly cacheable assets" },
      { id: "c", text: "A nightly batch job with no latency requirements" },
      { id: "d", text: "A data warehouse for analytics" },
    ],
    correct: ["a"],
    explanation:
      "GA shines for non-cacheable, latency-sensitive TCP/UDP traffic. Cacheable web content is better served by CloudFront.",
    difficulty: "medium",
    services: ["global-accelerator"],
  },
  {
    id: "saa-d3-064",
    section: "d3-high-performing",
    subtopic: "global-accelerator",
    type: "single",
    prompt: "What is a benefit of Global Accelerator's two static anycast IPs?",
    options: [
      { id: "a", text: "Clients use fixed IPs while GA routes to the optimal healthy endpoint and fails over quickly across Regions" },
      { id: "b", text: "It caches HTTP responses at the edge" },
      { id: "c", text: "It encrypts data at rest automatically" },
      { id: "d", text: "It replaces IAM for authentication" },
    ],
    correct: ["a"],
    explanation:
      "The fixed anycast IPs simplify allow-listing and DNS, while GA transparently directs traffic to the best healthy endpoint and fails over fast.",
    difficulty: "medium",
    services: ["global-accelerator"],
  },
  {
    id: "saa-d3-065",
    section: "d3-high-performing",
    subtopic: "global-accelerator",
    type: "single",
    prompt: "How does Global Accelerator route user traffic?",
    options: [
      { id: "a", text: "Users enter the AWS network at the nearest edge, then traffic travels over the AWS backbone to the closest healthy application endpoint" },
      { id: "b", text: "Randomly across all endpoints" },
      { id: "c", text: "Only over the public internet the whole way" },
      { id: "d", text: "Only to a single fixed Region" },
    ],
    correct: ["a"],
    explanation:
      "GA gets traffic onto the AWS global backbone at a nearby edge, improving latency and reliability versus traversing the public internet end-to-end.",
    difficulty: "medium",
    services: ["global-accelerator"],
  },
  {
    id: "saa-d3-066",
    section: "d3-high-performing",
    subtopic: "fsx",
    type: "single",
    prompt: "What is Amazon FSx?",
    options: [
      { id: "a", text: "Managed third-party / high-performance file systems (Windows File Server, Lustre, NetApp ONTAP, OpenZFS)" },
      { id: "b", text: "An object storage service" },
      { id: "c", text: "A relational database" },
      { id: "d", text: "A content delivery network" },
    ],
    correct: ["a"],
    explanation:
      "FSx offers fully managed file systems in several flavors, each tuned to specific workloads, beyond what EFS (Linux NFS) provides.",
    difficulty: "easy",
    services: ["fsx"],
  },
  {
    id: "saa-d3-067",
    section: "d3-high-performing",
    subtopic: "fsx",
    type: "single",
    prompt:
      "You need a managed Windows-native shared file system (SMB, NTFS, Active Directory integration) for EC2 Windows instances. Which service?",
    options: [
      { id: "a", text: "Amazon FSx for Windows File Server" },
      { id: "b", text: "Amazon EFS" },
      { id: "c", text: "Amazon S3" },
      { id: "d", text: "EC2 instance store" },
    ],
    correct: ["a"],
    explanation:
      "FSx for Windows File Server provides native SMB/NTFS with AD integration. EFS is Linux/NFS and isn't a Windows file share.",
    difficulty: "medium",
    services: ["fsx"],
  },
  {
    id: "saa-d3-068",
    section: "d3-high-performing",
    subtopic: "fsx",
    type: "single",
    prompt:
      "Which service provides a high-performance file system for HPC, machine learning, and big-data workloads, often integrated with S3?",
    options: [
      { id: "a", text: "Amazon FSx for Lustre" },
      { id: "b", text: "Amazon EFS" },
      { id: "c", text: "Amazon S3 Glacier" },
      { id: "d", text: "AWS Storage Gateway" },
    ],
    correct: ["a"],
    explanation:
      "FSx for Lustre is a high-throughput, low-latency parallel file system for HPC/ML, and can link to an S3 data repository.",
    difficulty: "medium",
    services: ["fsx"],
  },
  {
    id: "saa-d3-069",
    section: "d3-high-performing",
    subtopic: "fsx",
    type: "single",
    prompt:
      "A Linux fleet just needs a simple shared NFS file system across AZs. What's the simplest fit?",
    options: [
      { id: "a", text: "Amazon EFS" },
      { id: "b", text: "Amazon FSx for Windows File Server" },
      { id: "c", text: "Amazon FSx for Lustre" },
      { id: "d", text: "EC2 instance store" },
    ],
    correct: ["a"],
    explanation:
      "EFS is the simple managed NFS choice for Linux across AZs. FSx flavors target Windows or specialized high-performance needs.",
    difficulty: "easy",
    services: ["efs", "fsx"],
  },
  {
    id: "saa-d3-070",
    section: "d3-high-performing",
    subtopic: "fsx",
    type: "single",
    prompt: "Which statement about Amazon FSx is correct?",
    options: [
      { id: "a", text: "It offers fully managed file systems with multiple engines tuned for different workloads, and can integrate with Active Directory" },
      { id: "b", text: "It is object storage" },
      { id: "c", text: "It is only for cold archival" },
      { id: "d", text: "It cannot integrate with Active Directory" },
    ],
    correct: ["a"],
    explanation:
      "FSx is managed file storage with multiple engines (Windows, Lustre, ONTAP, OpenZFS); the Windows engine integrates with Active Directory.",
    difficulty: "medium",
    services: ["fsx"],
  },
  {
    id: "saa-d3-071",
    section: "d3-high-performing",
    subtopic: "hybrid-storage",
    type: "single",
    prompt:
      "You must migrate 500 TB and your network link would take months. How do you choose between Snowball and DataSync?",
    options: [
      { id: "a", text: "Use Snowball (offline, ship a device) for very large data over slow links; use DataSync for ongoing network transfers" },
      { id: "b", text: "Always use DataSync regardless of size" },
      { id: "c", text: "Always use Direct Connect" },
      { id: "d", text: "Always use Transfer Family" },
    ],
    correct: ["a"],
    explanation:
      "Offline shipping (Snowball) wins for huge one-time transfers over poor links; DataSync is for repeated/online network-based transfers.",
    difficulty: "medium",
    services: ["snow-family", "datasync"],
  },
  {
    id: "saa-d3-072",
    section: "d3-high-performing",
    subtopic: "hybrid-storage",
    type: "single",
    prompt:
      "An on-premises app needs to write files that are stored as objects in S3, with frequently used data cached locally for low latency. Which Storage Gateway type?",
    options: [
      { id: "a", text: "Amazon S3 File Gateway" },
      { id: "b", text: "Volume Gateway" },
      { id: "c", text: "Tape Gateway" },
      { id: "d", text: "AWS Snowcone" },
    ],
    correct: ["a"],
    explanation:
      "S3 File Gateway presents an NFS/SMB interface on-prem while storing files as S3 objects, caching hot data locally. Volume Gateway is block; Tape Gateway replaces physical tape backups.",
    difficulty: "medium",
    services: ["storage-gateway", "s3"],
  },
  {
    id: "saa-d3-073",
    section: "d3-high-performing",
    subtopic: "kinesis",
    type: "single",
    prompt: "What is Amazon Kinesis Data Streams?",
    options: [
      { id: "a", text: "A real-time data streaming service where multiple consumers can read the same data, with a retention window for replay" },
      { id: "b", text: "A queue where each message is consumed once" },
      { id: "c", text: "A relational database" },
      { id: "d", text: "A content delivery network" },
    ],
    correct: ["a"],
    explanation:
      "Kinesis Data Streams ingests high-volume real-time data; multiple consumers can independently read and replay records within the retention period.",
    difficulty: "medium",
    services: ["kinesis"],
  },
  {
    id: "saa-d3-074",
    section: "d3-high-performing",
    subtopic: "kinesis",
    type: "single",
    prompt: "What is Amazon Data Firehose (Kinesis Data Firehose)?",
    options: [
      { id: "a", text: "A fully managed service that delivers streaming data to destinations like S3, Redshift, and OpenSearch in near-real-time, with no servers to manage" },
      { id: "b", text: "A pull-based queue" },
      { id: "c", text: "A block storage volume" },
      { id: "d", text: "A DNS service" },
    ],
    correct: ["a"],
    explanation:
      "Firehose is the easy, fully managed way to load streaming data into stores/analytics destinations; it buffers and delivers without you running consumers.",
    difficulty: "medium",
    services: ["firehose"],
  },
  {
    id: "saa-d3-075",
    section: "d3-high-performing",
    subtopic: "kinesis",
    type: "single",
    prompt:
      "What is the main difference between Kinesis Data Streams and Amazon Data Firehose?",
    options: [
      { id: "a", text: "Data Streams gives low-latency streams with custom consumers and replay; Firehose is fully managed delivery to destinations with no consumer code" },
      { id: "b", text: "They are identical" },
      { id: "c", text: "Firehose supports replay of records" },
      { id: "d", text: "Data Streams cannot scale" },
    ],
    correct: ["a"],
    explanation:
      "Use Data Streams when you need custom real-time processing and replay; use Firehose when you just need managed delivery to S3/Redshift/OpenSearch.",
    difficulty: "medium",
    services: ["kinesis", "firehose"],
  },
  {
    id: "saa-d3-076",
    section: "d3-high-performing",
    subtopic: "kinesis",
    type: "single",
    prompt: "Which workload best fits Kinesis Data Streams?",
    options: [
      { id: "a", text: "Ingesting high-volume real-time data (clickstreams, IoT, logs) for one or more real-time consumers" },
      { id: "b", text: "Long-term cold archival" },
      { id: "c", text: "Hosting a static website" },
      { id: "d", text: "Running a relational database" },
    ],
    correct: ["a"],
    explanation:
      "Kinesis Data Streams targets real-time ingestion and processing of streaming data at scale, often feeding analytics or multiple consumers.",
    difficulty: "easy",
    services: ["kinesis"],
  },
  {
    id: "saa-d3-077",
    section: "d3-high-performing",
    subtopic: "ecs-fargate",
    type: "single",
    prompt:
      "How do you scale an Amazon ECS service for variable load and distribute incoming traffic across its tasks?",
    options: [
      { id: "a", text: "Use ECS Service Auto Scaling for the tasks and an Application Load Balancer in front of the service" },
      { id: "b", text: "Manually launch tasks as needed" },
      { id: "c", text: "Use Amazon Route 53 alone to scale tasks" },
      { id: "d", text: "Store tasks on instance store volumes" },
    ],
    correct: ["a"],
    explanation:
      "ECS Service Auto Scaling adjusts the number of running tasks based on metrics, and an ALB registers/deregisters tasks as targets to spread traffic.",
    difficulty: "medium",
    services: ["ecs", "alb"],
  },
  {
    id: "saa-d3-078",
    section: "d3-high-performing",
    subtopic: "lambda-advanced",
    type: "single",
    prompt: "Which is a key AWS Lambda limit to remember?",
    options: [
      { id: "a", text: "A maximum execution timeout of 15 minutes per invocation" },
      { id: "b", text: "Unlimited execution time" },
      { id: "c", text: "No memory limit at all" },
      { id: "d", text: "A minimum run time of 1 hour" },
    ],
    correct: ["a"],
    explanation:
      "Lambda functions can run up to 15 minutes per invocation. Long-running jobs should use ECS/Fargate, Step Functions, or batch instead.",
    difficulty: "medium",
    services: ["lambda"],
  },
  {
    id: "saa-d3-079",
    section: "d3-high-performing",
    subtopic: "lambda-advanced",
    type: "single",
    prompt: "What does AWS Lambda provisioned concurrency address?",
    options: [
      { id: "a", text: "It keeps function instances initialized and warm, eliminating cold-start latency for latency-sensitive workloads" },
      { id: "b", text: "It reduces storage costs" },
      { id: "c", text: "It encrypts the function code" },
      { id: "d", text: "It replaces API Gateway" },
    ],
    correct: ["a"],
    explanation:
      "Provisioned concurrency pre-warms a set number of execution environments so requests avoid cold starts. Reserved concurrency caps/guarantees how many can run.",
    difficulty: "hard",
    services: ["lambda"],
  },
  {
    id: "saa-d3-080",
    section: "d3-high-performing",
    subtopic: "lambda-advanced",
    type: "single",
    prompt: "What does AWS Lambda SnapStart do?",
    options: [
      { id: "a", text: "Reduces cold-start times (notably for Java) by resuming from a pre-initialized snapshot" },
      { id: "b", text: "Increases the timeout to one hour" },
      { id: "c", text: "Adds a built-in database" },
      { id: "d", text: "Encrypts the function's logs" },
    ],
    correct: ["a"],
    explanation:
      "SnapStart caches a snapshot of the initialized function and restores from it, dramatically cutting cold-start latency for supported runtimes.",
    difficulty: "hard",
    services: ["lambda"],
  },
  {
    id: "saa-d3-081",
    section: "d3-high-performing",
    subtopic: "lambda-advanced",
    type: "single",
    prompt:
      "How can you run lightweight code at CloudFront edge locations to customize requests/responses close to users?",
    options: [
      { id: "a", text: "Lambda@Edge or CloudFront Functions" },
      { id: "b", text: "A standard Lambda in a single Region" },
      { id: "c", text: "An EC2 instance in every Region" },
      { id: "d", text: "Amazon Route 53" },
    ],
    correct: ["a"],
    explanation:
      "Lambda@Edge and CloudFront Functions execute at edge locations to manipulate requests/responses (e.g., headers, redirects, auth) near the viewer.",
    difficulty: "medium",
    services: ["lambda", "cloudfront"],
  },
  {
    id: "saa-d3-082",
    section: "d3-high-performing",
    subtopic: "dynamodb",
    type: "single",
    prompt: "What is Amazon DynamoDB?",
    options: [
      { id: "a", text: "A fully managed, serverless NoSQL key-value/document database with single-digit-millisecond latency at any scale" },
      { id: "b", text: "A managed relational database" },
      { id: "c", text: "An object storage service" },
      { id: "d", text: "A message queue" },
    ],
    correct: ["a"],
    explanation:
      "DynamoDB is AWS's serverless NoSQL database delivering consistent low-latency performance and seamless scaling.",
    difficulty: "easy",
    services: ["dynamodb"],
  },
  {
    id: "saa-d3-083",
    section: "d3-high-performing",
    subtopic: "dynamodb",
    type: "single",
    prompt: "Which workload best fits Amazon DynamoDB?",
    options: [
      { id: "a", text: "High-scale, low-latency key-value/document access with a flexible schema" },
      { id: "b", text: "Complex multi-table SQL joins and transactions over a normalized schema" },
      { id: "c", text: "Object/blob storage of large media files" },
      { id: "d", text: "Long-term cold archival" },
    ],
    correct: ["a"],
    explanation:
      "DynamoDB shines for high-throughput key-value/document patterns. Heavy relational joins/transactions suit RDS/Aurora; big blobs go to S3.",
    difficulty: "medium",
    services: ["dynamodb"],
  },
  {
    id: "saa-d3-084",
    section: "d3-high-performing",
    subtopic: "dynamodb",
    type: "single",
    prompt:
      "How do you add microsecond-latency read caching in front of DynamoDB?",
    options: [
      { id: "a", text: "DynamoDB Accelerator (DAX)" },
      { id: "b", text: "A standard read replica" },
      { id: "c", text: "Amazon CloudFront" },
      { id: "d", text: "An Application Load Balancer" },
    ],
    correct: ["a"],
    explanation:
      "DAX is a purpose-built, in-memory cache for DynamoDB delivering microsecond read latency with no application rewrite of DynamoDB API calls.",
    difficulty: "medium",
    services: ["dynamodb", "dynamodb-dax"],
  },
  {
    id: "saa-d3-085",
    section: "d3-high-performing",
    subtopic: "api-gateway",
    type: "single",
    prompt: "How can Amazon API Gateway improve performance and protect backends?",
    options: [
      { id: "a", text: "Enable response caching and apply throttling / rate limiting on requests" },
      { id: "b", text: "By encrypting EBS volumes" },
      { id: "c", text: "By replicating S3 buckets" },
      { id: "d", text: "By hosting containers" },
    ],
    correct: ["a"],
    explanation:
      "API Gateway can cache responses to reduce backend calls/latency and throttle requests to protect downstream services from spikes.",
    difficulty: "medium",
    services: ["api-gateway"],
  },
  {
    id: "saa-d3-086",
    section: "d3-high-performing",
    subtopic: "serverless-micro-dist",
    type: "single",
    prompt:
      "You must distribute large software update files to users worldwide quickly and cost-effectively. Which design is best?",
    options: [
      { id: "a", text: "Store the files in Amazon S3 and serve them through Amazon CloudFront (edge caching reduces latency and origin egress)" },
      { id: "b", text: "Serve all downloads from a single EC2 instance" },
      { id: "c", text: "Email the files to each user" },
      { id: "d", text: "Use EBS Multi-Attach to share the files" },
    ],
    correct: ["a"],
    explanation:
      "S3 as durable origin plus CloudFront edge caching delivers global, low-latency downloads while cutting repeated origin data-transfer costs.",
    difficulty: "easy",
    services: ["s3", "cloudfront"],
  },
  {
    id: "saa-d3-087",
    section: "d3-high-performing",
    subtopic: "db-choice",
    type: "single",
    prompt:
      "A workload needs ACID transactions and complex SQL joins (classic OLTP). Which AWS database fits?",
    options: [
      { id: "a", text: "Amazon RDS or Amazon Aurora (relational)" },
      { id: "b", text: "Amazon DynamoDB" },
      { id: "c", text: "Amazon Neptune" },
      { id: "d", text: "Amazon Timestream" },
    ],
    correct: ["a"],
    explanation:
      "Relational engines (RDS/Aurora) provide ACID transactions and rich SQL joins for OLTP. DynamoDB is NoSQL; Neptune is graph; Timestream is time-series.",
    difficulty: "easy",
    services: ["rds", "aurora"],
  },
  {
    id: "saa-d3-088",
    section: "d3-high-performing",
    subtopic: "db-choice",
    type: "single",
    prompt:
      "A high-scale app needs single-digit-millisecond key-value access with a flexible schema and massive throughput. Which database?",
    options: [
      { id: "a", text: "Amazon DynamoDB" },
      { id: "b", text: "Amazon RDS" },
      { id: "c", text: "Amazon Redshift" },
      { id: "d", text: "Amazon Neptune" },
    ],
    correct: ["a"],
    explanation:
      "DynamoDB is the serverless NoSQL choice for high-scale, low-latency key-value/document workloads.",
    difficulty: "easy",
    services: ["dynamodb"],
  },
  {
    id: "saa-d3-089",
    section: "d3-high-performing",
    subtopic: "db-choice",
    type: "single",
    prompt:
      "You need complex analytical queries (OLAP) over very large datasets for BI and reporting. Which AWS database?",
    options: [
      { id: "a", text: "Amazon Redshift (data warehouse)" },
      { id: "b", text: "Amazon DynamoDB" },
      { id: "c", text: "Amazon RDS sized for OLTP" },
      { id: "d", text: "Amazon ElastiCache" },
    ],
    correct: ["a"],
    explanation:
      "Redshift is the columnar, MPP data warehouse for OLAP/analytics. OLTP databases and key-value/cache stores aren't built for large analytical scans.",
    difficulty: "medium",
    services: ["redshift"],
  },
  {
    id: "saa-d3-090",
    section: "d3-high-performing",
    subtopic: "db-choice",
    type: "single",
    prompt:
      "You need to cache frequently accessed data in memory to cut latency and database load. Which service?",
    options: [
      { id: "a", text: "Amazon ElastiCache" },
      { id: "b", text: "An RDS read replica only" },
      { id: "c", text: "Amazon S3" },
      { id: "d", text: "Amazon Neptune" },
    ],
    correct: ["a"],
    explanation:
      "ElastiCache (Redis/Memcached) is the in-memory caching layer for microsecond/millisecond reads and database offload.",
    difficulty: "easy",
    services: ["elasticache"],
  },
  {
    id: "saa-d3-091",
    section: "d3-high-performing",
    subtopic: "db-choice",
    type: "single",
    prompt: "What is AWS's guidance on choosing databases?",
    options: [
      { id: "a", text: "Use purpose-built databases matched to the data model and access pattern, rather than forcing one database to do everything" },
      { id: "b", text: "Always use a single relational database for every workload" },
      { id: "c", text: "Always use DynamoDB for everything" },
      { id: "d", text: "Avoid managed databases entirely" },
    ],
    correct: ["a"],
    explanation:
      "AWS promotes purpose-built databases (relational, key-value, document, graph, time-series, ledger, in-memory, warehouse) chosen per workload.",
    difficulty: "medium",
    services: ["rds", "dynamodb"],
  },
  {
    id: "saa-d3-092",
    section: "d3-high-performing",
    subtopic: "purpose-built-db",
    type: "single",
    prompt: "Which AWS database is MongoDB-compatible (a managed document database)?",
    options: [
      { id: "a", text: "Amazon DocumentDB" },
      { id: "b", text: "Amazon Neptune" },
      { id: "c", text: "Amazon Keyspaces" },
      { id: "d", text: "Amazon Timestream" },
    ],
    correct: ["a"],
    explanation:
      "Amazon DocumentDB is a managed document database with MongoDB compatibility.",
    difficulty: "medium",
    services: ["documentdb"],
  },
  {
    id: "saa-d3-093",
    section: "d3-high-performing",
    subtopic: "purpose-built-db",
    type: "single",
    prompt:
      "Which AWS database is a managed graph database for highly connected data (social networks, recommendations, fraud detection)?",
    options: [
      { id: "a", text: "Amazon Neptune" },
      { id: "b", text: "Amazon DocumentDB" },
      { id: "c", text: "Amazon DynamoDB" },
      { id: "d", text: "Amazon Redshift" },
    ],
    correct: ["a"],
    explanation:
      "Amazon Neptune is the managed graph database, ideal for relationship-heavy queries.",
    difficulty: "medium",
    services: ["neptune"],
  },
  {
    id: "saa-d3-094",
    section: "d3-high-performing",
    subtopic: "purpose-built-db",
    type: "single",
    prompt: "Which AWS database is compatible with Apache Cassandra (wide-column)?",
    options: [
      { id: "a", text: "Amazon Keyspaces (for Apache Cassandra)" },
      { id: "b", text: "Amazon Neptune" },
      { id: "c", text: "Amazon Aurora" },
      { id: "d", text: "Amazon Timestream" },
    ],
    correct: ["a"],
    explanation:
      "Amazon Keyspaces is a managed, serverless Cassandra-compatible (wide-column) database.",
    difficulty: "medium",
    services: ["keyspaces"],
  },
  {
    id: "saa-d3-095",
    section: "d3-high-performing",
    subtopic: "purpose-built-db",
    type: "single",
    prompt:
      "Which AWS database is purpose-built for time-series data (IoT metrics, telemetry, monitoring)?",
    options: [
      { id: "a", text: "Amazon Timestream" },
      { id: "b", text: "Amazon DynamoDB" },
      { id: "c", text: "Amazon Neptune" },
      { id: "d", text: "Amazon DocumentDB" },
    ],
    correct: ["a"],
    explanation:
      "Amazon Timestream is optimized for time-series workloads with built-in time-based functions and tiered storage.",
    difficulty: "medium",
    services: ["timestream"],
  },
  {
    id: "saa-d3-096",
    section: "d3-high-performing",
    subtopic: "purpose-built-db",
    type: "single",
    prompt:
      "Which AWS database provides an immutable, cryptographically verifiable ledger of all changes (e.g., for audit/financial records)?",
    options: [
      { id: "a", text: "Amazon QLDB (Quantum Ledger Database)" },
      { id: "b", text: "Amazon DynamoDB" },
      { id: "c", text: "Amazon Neptune" },
      { id: "d", text: "Amazon RDS" },
    ],
    correct: ["a"],
    explanation:
      "Amazon QLDB maintains a complete, immutable, verifiable history of changes — useful for systems of record needing an audit trail.",
    difficulty: "medium",
    services: ["qldb"],
  },
  {
    id: "saa-d3-097",
    section: "d3-high-performing",
    subtopic: "analytics-query",
    type: "single",
    prompt: "What is Amazon Athena?",
    options: [
      { id: "a", text: "A serverless service to run SQL queries directly against data in Amazon S3, paying per query / data scanned" },
      { id: "b", text: "A managed relational database" },
      { id: "c", text: "A container orchestration service" },
      { id: "d", text: "A content delivery network" },
    ],
    correct: ["a"],
    explanation:
      "Athena lets you query S3 data with standard SQL without managing infrastructure; you pay for the data scanned (reduce cost with columnar formats/partitioning).",
    difficulty: "easy",
    services: ["athena", "s3"],
  },
  {
    id: "saa-d3-098",
    section: "d3-high-performing",
    subtopic: "analytics-query",
    type: "single",
    prompt: "What is Amazon Redshift?",
    options: [
      { id: "a", text: "A managed, petabyte-scale columnar data warehouse (MPP) for OLAP/BI analytics" },
      { id: "b", text: "A NoSQL key-value database" },
      { id: "c", text: "An in-memory cache" },
      { id: "d", text: "A message queue" },
    ],
    correct: ["a"],
    explanation:
      "Redshift is AWS's columnar, massively parallel data warehouse built for complex analytical queries over large datasets.",
    difficulty: "easy",
    services: ["redshift"],
  },
  {
    id: "saa-d3-099",
    section: "d3-high-performing",
    subtopic: "analytics-query",
    type: "single",
    prompt: "When would you prefer Amazon Athena over Amazon Redshift?",
    options: [
      { id: "a", text: "For ad-hoc, serverless SQL queries directly on S3 data without provisioning or loading into a cluster" },
      { id: "b", text: "For sustained, high-concurrency complex analytics where you load and model the data" },
      { id: "c", text: "For key-value lookups" },
      { id: "d", text: "For in-memory caching" },
    ],
    correct: ["a"],
    explanation:
      "Athena suits occasional/ad-hoc queries on S3 with no cluster to manage. Redshift suits heavy, repeated, complex analytics on data loaded into the warehouse.",
    difficulty: "medium",
    services: ["athena", "redshift"],
  },
  {
    id: "saa-d3-100",
    section: "d3-high-performing",
    subtopic: "analytics-query",
    type: "single",
    prompt: "What is Amazon QuickSight?",
    options: [
      { id: "a", text: "A serverless business intelligence (BI) service for dashboards and data visualizations" },
      { id: "b", text: "A relational database" },
      { id: "c", text: "An ETL service" },
      { id: "d", text: "A container registry" },
    ],
    correct: ["a"],
    explanation:
      "QuickSight builds interactive dashboards/visualizations over many data sources (S3/Athena/Redshift/RDS, etc.) without managing servers.",
    difficulty: "easy",
    services: ["quicksight"],
  },
  {
    id: "saa-d3-101",
    section: "d3-high-performing",
    subtopic: "analytics-query",
    type: "single",
    prompt:
      "Which service provides search and analytics over logs and operational data (formerly Elasticsearch Service)?",
    options: [
      { id: "a", text: "Amazon OpenSearch Service" },
      { id: "b", text: "Amazon Redshift" },
      { id: "c", text: "Amazon Athena" },
      { id: "d", text: "Amazon QuickSight" },
    ],
    correct: ["a"],
    explanation:
      "Amazon OpenSearch Service (formerly Elasticsearch Service) is used for full-text search, log analytics, and observability dashboards.",
    difficulty: "medium",
    services: ["opensearch"],
  },
  {
    id: "saa-d3-102",
    section: "d3-high-performing",
    subtopic: "etl-datalake",
    type: "single",
    prompt: "What is AWS Glue?",
    options: [
      { id: "a", text: "A serverless ETL (extract, transform, load) service, with a data catalog, for preparing and moving data" },
      { id: "b", text: "A relational database engine" },
      { id: "c", text: "A load balancer" },
      { id: "d", text: "A CDN" },
    ],
    correct: ["a"],
    explanation:
      "Glue runs serverless ETL jobs and provides a metadata catalog, commonly used to prepare data for analytics (Athena, Redshift, EMR).",
    difficulty: "easy",
    services: ["glue"],
  },
  {
    id: "saa-d3-103",
    section: "d3-high-performing",
    subtopic: "etl-datalake",
    type: "single",
    prompt: "What does the AWS Glue Data Catalog provide?",
    options: [
      { id: "a", text: "A central metadata repository of your datasets (tables/schemas) used by Athena, Redshift Spectrum, and EMR" },
      { id: "b", text: "Block storage volumes" },
      { id: "c", text: "A DNS service" },
      { id: "d", text: "A message queue" },
    ],
    correct: ["a"],
    explanation:
      "The Glue Data Catalog stores table definitions/schemas so query engines (Athena, Redshift Spectrum, EMR) can discover and read your data.",
    difficulty: "medium",
    services: ["glue"],
  },
  {
    id: "saa-d3-104",
    section: "d3-high-performing",
    subtopic: "etl-datalake",
    type: "single",
    prompt: "What is AWS Lake Formation?",
    options: [
      { id: "a", text: "A service to build and secure data lakes on S3, with centralized, fine-grained permissions" },
      { id: "b", text: "A relational database" },
      { id: "c", text: "A container orchestrator" },
      { id: "d", text: "A CDN" },
    ],
    correct: ["a"],
    explanation:
      "Lake Formation simplifies setting up data lakes on S3 and centrally manages fine-grained access permissions across analytics services.",
    difficulty: "medium",
    services: ["lake-formation", "s3"],
  },
  {
    id: "saa-d3-105",
    section: "d3-high-performing",
    subtopic: "etl-datalake",
    type: "single",
    prompt: "What is Amazon EMR?",
    options: [
      { id: "a", text: "A managed big-data platform running frameworks like Apache Hadoop, Spark, and Hive on clusters" },
      { id: "b", text: "A serverless SQL-on-S3 query tool" },
      { id: "c", text: "A NoSQL database" },
      { id: "d", text: "A CDN" },
    ],
    correct: ["a"],
    explanation:
      "Amazon EMR provisions and manages clusters for large-scale data processing with Hadoop/Spark/Hive/Presto and more.",
    difficulty: "medium",
    services: ["emr"],
  },
  {
    id: "saa-d3-106",
    section: "d3-high-performing",
    subtopic: "etl-datalake",
    type: "single",
    prompt: "Which service is the foundation (storage layer) of a typical AWS data lake?",
    options: [
      { id: "a", text: "Amazon S3" },
      { id: "b", text: "Amazon EBS" },
      { id: "c", text: "Amazon RDS" },
      { id: "d", text: "Instance store" },
    ],
    correct: ["a"],
    explanation:
      "S3 is the durable, scalable, low-cost object store at the center of AWS data lakes, queried by Athena/Redshift Spectrum and cataloged by Glue/Lake Formation.",
    difficulty: "easy",
    services: ["s3"],
  },
  {
    id: "saa-d3-107",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt: "Which AWS service analyzes images and videos (object/face/label detection, content moderation)?",
    options: [
      { id: "a", text: "Amazon Rekognition" },
      { id: "b", text: "Amazon Comprehend" },
      { id: "c", text: "Amazon Polly" },
      { id: "d", text: "Amazon Translate" },
    ],
    correct: ["a"],
    explanation:
      "Rekognition provides image and video analysis (faces, objects, labels, moderation).",
    difficulty: "easy",
    services: ["rekognition"],
  },
  {
    id: "saa-d3-108",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt: "Which AWS service converts speech (audio) into text?",
    options: [
      { id: "a", text: "Amazon Transcribe" },
      { id: "b", text: "Amazon Polly" },
      { id: "c", text: "Amazon Rekognition" },
      { id: "d", text: "Amazon Translate" },
    ],
    correct: ["a"],
    explanation:
      "Transcribe is automatic speech recognition (audio → text). Polly does the reverse (text → speech).",
    difficulty: "easy",
    services: ["transcribe"],
  },
  {
    id: "saa-d3-109",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt: "Which AWS service converts text into lifelike speech (text-to-speech)?",
    options: [
      { id: "a", text: "Amazon Polly" },
      { id: "b", text: "Amazon Transcribe" },
      { id: "c", text: "Amazon Lex" },
      { id: "d", text: "Amazon Comprehend" },
    ],
    correct: ["a"],
    explanation:
      "Polly turns text into natural-sounding speech (text → audio).",
    difficulty: "easy",
    services: ["polly"],
  },
  {
    id: "saa-d3-110",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt: "Which AWS service performs language translation between languages?",
    options: [
      { id: "a", text: "Amazon Translate" },
      { id: "b", text: "Amazon Comprehend" },
      { id: "c", text: "Amazon Transcribe" },
      { id: "d", text: "Amazon Kendra" },
    ],
    correct: ["a"],
    explanation:
      "Amazon Translate provides neural machine translation across many languages.",
    difficulty: "easy",
    services: ["translate"],
  },
  {
    id: "saa-d3-111",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt:
      "Which AWS service uses NLP to find insights in text (sentiment, entities, key phrases, language)?",
    options: [
      { id: "a", text: "Amazon Comprehend" },
      { id: "b", text: "Amazon Rekognition" },
      { id: "c", text: "Amazon Polly" },
      { id: "d", text: "Amazon Textract" },
    ],
    correct: ["a"],
    explanation:
      "Comprehend is a natural-language-processing service for sentiment analysis, entity/key-phrase extraction, and language detection.",
    difficulty: "easy",
    services: ["comprehend"],
  },
  {
    id: "saa-d3-112",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt: "Which AWS service is used to build conversational chatbots (and powers Amazon Connect)?",
    options: [
      { id: "a", text: "Amazon Lex" },
      { id: "b", text: "Amazon Polly" },
      { id: "c", text: "Amazon Kendra" },
      { id: "d", text: "Amazon Translate" },
    ],
    correct: ["a"],
    explanation:
      "Amazon Lex builds conversational interfaces (chatbots) using the same tech as Alexa, and integrates with Amazon Connect contact centers.",
    difficulty: "easy",
    services: ["lex"],
  },
  {
    id: "saa-d3-113",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt: "Which AWS service is a fully managed platform to build, train, and deploy custom ML models?",
    options: [
      { id: "a", text: "Amazon SageMaker" },
      { id: "b", text: "Amazon Rekognition" },
      { id: "c", text: "Amazon Comprehend" },
      { id: "d", text: "Amazon Polly" },
    ],
    correct: ["a"],
    explanation:
      "SageMaker is the end-to-end ML platform for building, training, tuning, and deploying models. The others are pre-built AI services for specific tasks.",
    difficulty: "easy",
    services: ["sagemaker"],
  },
  {
    id: "saa-d3-114",
    section: "d3-high-performing",
    subtopic: "ai-ml-services",
    type: "single",
    prompt:
      "Which AWS service extracts text, forms, and tables from scanned documents (OCR+)?",
    options: [
      { id: "a", text: "Amazon Textract" },
      { id: "b", text: "Amazon Rekognition" },
      { id: "c", text: "Amazon Comprehend" },
      { id: "d", text: "Amazon Transcribe" },
    ],
    correct: ["a"],
    explanation:
      "Textract extracts printed/handwritten text plus structured form and table data from documents (beyond simple OCR).",
    difficulty: "easy",
    services: ["textract"],
  },
  {
    id: "saa-d3-115",
    section: "d3-high-performing",
    subtopic: "hybrid-networking",
    type: "single",
    prompt:
      "A company needs consistent, low-latency, high-throughput connectivity between its data center and AWS for a large data transfer workload. Which option is best?",
    options: [
      { id: "a", text: "AWS Direct Connect — a dedicated private physical connection with consistent performance" },
      { id: "b", text: "A Site-to-Site VPN over the public internet" },
      { id: "c", text: "VPC peering" },
      { id: "d", text: "A NAT gateway" },
    ],
    correct: ["a"],
    explanation:
      "Direct Connect provides a dedicated private link with predictable bandwidth and latency — better than a VPN, which rides the variable public internet.",
    difficulty: "medium",
    services: ["direct-connect"],
  },
  {
    id: "saa-d3-116",
    section: "d3-high-performing",
    subtopic: "vpc-connectivity",
    type: "single",
    prompt:
      "You need to connect hundreds of VPCs and on-premises networks with transitive routing through a single hub. Which service scales best?",
    options: [
      { id: "a", text: "AWS Transit Gateway — a central hub that connects many VPCs and on-prem networks with transitive routing" },
      { id: "b", text: "A full mesh of VPC peering connections" },
      { id: "c", text: "An internet gateway per VPC" },
      { id: "d", text: "A single NAT gateway" },
    ],
    correct: ["a"],
    explanation:
      "VPC peering is non-transitive and becomes a hard-to-manage mesh at scale. Transit Gateway is a hub-and-spoke router that connects thousands of VPCs and VPN/DX links with transitive routing.",
    difficulty: "medium",
    services: ["transit-gateway"],
  },
  {
    id: "saa-d3-117",
    section: "d3-high-performing",
    subtopic: "backup-transfer",
    type: "single",
    prompt:
      "You must repeatedly transfer large volumes of data from on-premises to AWS quickly over the network, with built-in encryption and validation. Which service accelerates this?",
    options: [
      { id: "a", text: "AWS DataSync — purpose-built to move data over the network faster than generic tools, with encryption and integrity checks" },
      { id: "b", text: "Amazon Athena" },
      { id: "c", text: "Amazon Polly" },
      { id: "d", text: "AWS Config" },
    ],
    correct: ["a"],
    explanation:
      "DataSync uses a purpose-built protocol/agent to move data over the network at high speed with encryption and validation — far faster than manual copy tools for large online transfers.",
    difficulty: "medium",
    services: ["datasync"],
  },
  {
    id: "saa-d3-118",
    section: "d3-high-performing",
    subtopic: "arch-patterns",
    type: "single",
    prompt:
      "Match each caching layer to its job: static/dynamic content at the edge, relational/session data in front of a database, and microsecond reads for DynamoDB.",
    options: [
      { id: "a", text: "CloudFront (edge content), ElastiCache (database/session cache), DAX (DynamoDB in-memory acceleration)" },
      { id: "b", text: "They all cache the same thing interchangeably" },
      { id: "c", text: "DAX caches edge content; CloudFront caches DynamoDB; ElastiCache is a CDN" },
      { id: "d", text: "ElastiCache is an edge cache; CloudFront fronts DynamoDB" },
    ],
    correct: ["a"],
    explanation:
      "Caching is layered: CloudFront caches content at edge locations, ElastiCache (Redis/Memcached) offloads databases and stores sessions, and DAX gives microsecond reads for DynamoDB. API Gateway caching is another layer for API responses.",
    difficulty: "medium",
    services: ["cloudfront", "elasticache", "dax"],
  },
  {
    id: "saa-d3-119",
    section: "d3-high-performing",
    subtopic: "hpc-availability",
    type: "single",
    prompt:
      "For a tightly-coupled HPC workload (MPI) needing the lowest inter-node latency on EC2, which combination is recommended?",
    options: [
      { id: "a", text: "A cluster placement group plus an Elastic Fabric Adapter (EFA) for low-latency, high-throughput node-to-node communication" },
      { id: "b", text: "A spread placement group across Regions" },
      { id: "c", text: "Instances in different VPCs connected by the internet" },
      { id: "d", text: "Burstable t-family instances with standard networking" },
    ],
    correct: ["a"],
    explanation:
      "HPC/MPI benefits from a cluster placement group (instances physically close) and EFA, which provides OS-bypass, low-latency networking for tightly-coupled parallel jobs.",
    difficulty: "hard",
    services: ["ec2", "efa"],
  },
  {
    id: "saa-d3-120",
    section: "d3-high-performing",
    subtopic: "hpc-availability",
    type: "single",
    prompt:
      "An HPC workload needs a shared, high-throughput, low-latency file system for thousands of cores processing large datasets. Which storage is the best fit?",
    options: [
      { id: "a", text: "Amazon FSx for Lustre" },
      { id: "b", text: "Amazon S3 Glacier Deep Archive" },
      { id: "c", text: "A single EBS gp2 volume" },
      { id: "d", text: "An RDS database" },
    ],
    correct: ["a"],
    explanation:
      "FSx for Lustre is a high-performance parallel file system designed for HPC, machine learning, and media workloads, and integrates with S3 for the underlying data.",
    difficulty: "medium",
    services: ["fsx", "fsx-lustre"],
  },
  {
    id: "saa-d3-121",
    section: "d3-high-performing",
    subtopic: "iac-deployment",
    type: "single",
    prompt: "What is AWS Amplify?",
    options: [
      { id: "a", text: "A set of tools and a hosting service to build and deploy full-stack web and mobile apps (frontend hosting, auth, APIs, storage)" },
      { id: "b", text: "A managed relational database" },
      { id: "c", text: "A batch-processing service" },
      { id: "d", text: "A DNS service" },
    ],
    correct: ["a"],
    explanation:
      "Amplify helps developers build and host full-stack apps quickly, providing frontend hosting (with CI/CD) plus backend building blocks like auth, APIs, and storage.",
    difficulty: "easy",
    services: ["amplify"],
  },
  {
    id: "saa-d3-122",
    section: "d3-high-performing",
    subtopic: "operations-mgmt",
    type: "single",
    prompt:
      "You need to run hundreds of thousands of batch compute jobs, with AWS managing the provisioning and scaling of the underlying compute. Which service is purpose-built for this?",
    options: [
      { id: "a", text: "AWS Batch" },
      { id: "b", text: "Amazon SES" },
      { id: "c", text: "Amazon Pinpoint" },
      { id: "d", text: "AWS Amplify" },
    ],
    correct: ["a"],
    explanation:
      "AWS Batch dynamically provisions and scales compute (EC2/Fargate, including Spot) to run batch jobs efficiently, without you managing the cluster. (For event-driven, short tasks, Lambda may fit instead.)",
    difficulty: "medium",
    services: ["batch"],
  },
];
