// Domain 4 — Design Cost-Optimized Architectures (20%)
// Question shape is documented in plan/01-architecture.md.
export const questions = [
  {
    id: "saa-d4-001",
    section: "d4-cost-optimized",
    subtopic: "s3-lifecycle",
    type: "single",
    prompt:
      "Log files in Amazon S3 are accessed frequently for 30 days, rarely for the next 90 days, and must be retained for 7 years for compliance but are almost never read after that. What is the MOST cost-effective approach?",
    options: [
      { id: "a", text: "Keep all objects in S3 Standard for 7 years" },
      { id: "b", text: "Use an S3 Lifecycle policy to transition to S3 Standard-IA, then to Glacier/Deep Archive over time" },
      { id: "c", text: "Delete the logs after 30 days" },
      { id: "d", text: "Store the logs on a large EBS volume" },
    ],
    correct: ["b"],
    explanation:
      "A lifecycle policy automatically moves objects to cheaper tiers as access drops (Standard-IA, then Glacier/Glacier Deep Archive for long-term archive), matching cost to access pattern. Keeping everything in Standard is expensive; deleting violates retention; EBS is costlier and not designed for archival.",
    difficulty: "medium",
    services: ["s3", "s3-glacier"],
  },
  {
    id: "saa-d4-002",
    section: "d4-cost-optimized",
    type: "single",
    prompt:
      "A batch image-processing job is fault tolerant, can be interrupted and resumed, and has flexible completion times. Which EC2 purchasing option minimizes cost?",
    options: [
      { id: "a", text: "On-Demand Instances" },
      { id: "b", text: "Spot Instances" },
      { id: "c", text: "Reserved Instances" },
      { id: "d", text: "Dedicated Hosts" },
    ],
    correct: ["b"],
    explanation:
      "Spot Instances offer the largest discount and are ideal for interruption-tolerant, flexible batch work. On-Demand is more expensive for this case; Reserved/Savings Plans suit steady long-running workloads; Dedicated Hosts are for licensing/compliance, not cost minimization here.",
    difficulty: "easy",
    services: ["ec2", "spot"],
  },
  {
    id: "saa-d4-003",
    section: "d4-cost-optimized",
    type: "single",
    prompt:
      "A company runs a steady, predictable production workload on EC2 24/7 for at least the next three years. Which purchasing model offers the best cost savings while keeping that capacity?",
    options: [
      { id: "a", text: "Spot Instances" },
      { id: "b", text: "On-Demand Instances" },
      { id: "c", text: "Compute Savings Plans or Reserved Instances" },
      { id: "d", text: "Dedicated Hosts billed On-Demand" },
    ],
    correct: ["c"],
    explanation:
      "For steady, long-term usage, a 1- or 3-year Savings Plan or Reserved Instance commitment provides large discounts over On-Demand. Spot can be reclaimed and is unsuitable for always-on production; On-Demand and On-Demand Dedicated Hosts are the most expensive for steady use.",
    difficulty: "easy",
    services: ["ec2", "savings-plans"],
  },
  {
    id: "saa-d4-004",
    section: "d4-cost-optimized",
    subtopic: "s3-storage-classes",
    type: "single",
    prompt:
      "A team stores objects in S3 but cannot predict access patterns, which change unpredictably over time. They want to optimize storage cost automatically without performance impact or retrieval fees for tier changes. Which S3 storage class should they choose?",
    options: [
      { id: "a", text: "S3 Standard" },
      { id: "b", text: "S3 Intelligent-Tiering" },
      { id: "c", text: "S3 One Zone-IA" },
      { id: "d", text: "S3 Glacier Deep Archive" },
    ],
    correct: ["b"],
    explanation:
      "S3 Intelligent-Tiering automatically moves objects between access tiers based on usage with no retrieval fees for those movements, ideal for unknown or changing access patterns. Standard is costlier for cold data; One Zone-IA reduces availability; Deep Archive is for rarely accessed long-term archives.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-005",
    section: "d4-cost-optimized",
    type: "single",
    prompt:
      "EC2 instances in private subnets pull large amounts of data from Amazon S3 through a NAT gateway, generating high NAT data-processing charges. What change reduces these costs?",
    options: [
      { id: "a", text: "Add a second NAT gateway" },
      { id: "b", text: "Create an S3 gateway VPC endpoint so S3 traffic bypasses the NAT gateway" },
      { id: "c", text: "Move the instances to public subnets with public IPs" },
      { id: "d", text: "Enable S3 Transfer Acceleration" },
    ],
    correct: ["b"],
    explanation:
      "An S3 gateway VPC endpoint routes S3 traffic privately within AWS at no per-GB charge, eliminating NAT data-processing fees for that traffic. Adding NAT capacity increases cost; public subnets reduce security; Transfer Acceleration speeds long-distance uploads but adds cost.",
    difficulty: "medium",
    services: ["vpc-endpoints", "s3", "nat-gateway"],
  },
  {
    id: "saa-d4-006",
    section: "d4-cost-optimized",
    subtopic: "dynamodb",
    type: "single",
    prompt:
      "A spiky, unpredictable workload uses Amazon DynamoDB. Traffic is near zero much of the day but has sudden large bursts. The team wants to avoid paying for idle provisioned capacity and avoid throttling during bursts. Which capacity mode is most cost-effective?",
    options: [
      { id: "a", text: "Provisioned capacity sized for peak" },
      { id: "b", text: "On-demand capacity mode" },
      { id: "c", text: "Provisioned capacity sized for average" },
      { id: "d", text: "A larger instance class" },
    ],
    correct: ["b"],
    explanation:
      "DynamoDB on-demand mode charges per request with no capacity planning, ideal for spiky, unpredictable traffic — you pay nothing for idle and absorb bursts without throttling. Provisioning for peak wastes money when idle; provisioning for average throttles during bursts; DynamoDB has no instance class.",
    difficulty: "medium",
    services: ["dynamodb"],
  },
  {
    id: "saa-d4-007",
    section: "d4-cost-optimized",
    type: "multi",
    prompt:
      "A solutions architect is asked to reduce the cost of a fleet of always-on EC2 instances that are consistently underutilized. Which TWO actions directly reduce cost? (Select TWO.)",
    options: [
      { id: "a", text: "Right-size the instances to a smaller type based on utilization metrics" },
      { id: "b", text: "Purchase a Compute Savings Plan for the steady baseline usage" },
      { id: "c", text: "Attach larger EBS volumes to each instance" },
      { id: "d", text: "Assign Elastic IPs to all instances" },
      { id: "e", text: "Enable detailed CloudWatch monitoring on every instance" },
    ],
    correct: ["a", "b"],
    explanation:
      "Right-sizing eliminates paying for unused capacity, and a Savings Plan discounts the steady baseline. Larger EBS volumes, Elastic IPs, and detailed monitoring add cost rather than reduce it.",
    difficulty: "medium",
    services: ["ec2", "savings-plans", "compute-optimizer"],
  },
  {
    id: "saa-d4-008",
    section: "d4-cost-optimized",
    type: "single",
    prompt:
      "A finance team needs to track AWS spend by project across multiple accounts and receive alerts when forecasted spend will exceed a threshold. Which combination of tools is appropriate?",
    options: [
      { id: "a", text: "Cost allocation tags with AWS Cost Explorer and AWS Budgets" },
      { id: "b", text: "Amazon CloudWatch metrics only" },
      { id: "c", text: "AWS CloudTrail event history" },
      { id: "d", text: "AWS Config rules" },
    ],
    correct: ["a"],
    explanation:
      "Cost allocation tags attribute spend to projects, Cost Explorer visualizes and analyzes it, and AWS Budgets sends alerts on actual or forecasted spend. CloudWatch, CloudTrail, and Config address metrics, API auditing, and configuration compliance — not cost reporting and budgeting.",
    difficulty: "medium",
    services: ["cost-explorer", "budgets", "cost-allocation-tags"],
  },
  {
    id: "saa-d4-009",
    section: "d4-cost-optimized",
    subtopic: "ec2-spot",
    type: "single",
    prompt:
      "Which EC2 Purchasing Option can provide the biggest discount, but is not suitable for critical jobs or databases?",
    options: [
      { id: "a", text: "Convertible Reserved Instances" },
      { id: "b", text: "Dedicated Hosts" },
      { id: "c", text: "Spot Instances" },
    ],
    correct: ["c"],
    explanation:
      "Spot Instances offer the deepest discount (up to ~90%) but can be reclaimed by AWS with little notice, so they are unsuitable for critical or stateful workloads like databases.",
    difficulty: "easy",
    services: ["ec2", "spot"],
  },
  {
    id: "saa-d4-010",
    section: "d4-cost-optimized",
    subtopic: "ec2-purchasing",
    type: "single",
    prompt: "How long can you reserve an EC2 Reserved Instance?",
    options: [
      { id: "a", text: "1 or 3 years" },
      { id: "b", text: "2 or 4 years" },
      { id: "c", text: "6 months or 1 year" },
      { id: "d", text: "Anytime between 1 and 3 years" },
    ],
    correct: ["a"],
    explanation:
      "Reserved Instances are purchased for a 1-year or 3-year term, with larger discounts for the longer commitment.",
    difficulty: "easy",
    services: ["ec2", "reserved-instances"],
  },
  {
    id: "saa-d4-011",
    section: "d4-cost-optimized",
    subtopic: "ec2-purchasing",
    type: "single",
    prompt:
      "Which EC2 Purchasing Option should you use for an application you plan to run on a server continuously for 1 year?",
    options: [
      { id: "a", text: "Reserved Instances" },
      { id: "b", text: "Spot Instances" },
      { id: "c", text: "On-Demand Instances" },
    ],
    correct: ["a"],
    explanation:
      "For steady, predictable usage over a full year, Reserved Instances (or a Savings Plan) provide a significant discount in exchange for the commitment. Spot can be reclaimed; On-Demand is the most expensive for continuous use.",
    difficulty: "easy",
    services: ["ec2", "reserved-instances"],
  },
  {
    id: "saa-d4-012",
    section: "d4-cost-optimized",
    subtopic: "ec2-purchasing",
    type: "single",
    prompt:
      "Your company has strict compliance requirements that applications run on dedicated physical servers, and you need to use your own server-bound software license to reduce costs. Which EC2 Purchasing Option is suitable?",
    options: [
      { id: "a", text: "Convertible Reserved Instances" },
      { id: "b", text: "Dedicated Hosts" },
      { id: "c", text: "Spot Instances" },
    ],
    correct: ["b"],
    explanation:
      "Dedicated Hosts give you a physical server fully dedicated to you, which supports strict compliance and bring-your-own-license (BYOL) models that are tied to physical sockets/cores.",
    difficulty: "medium",
    services: ["ec2", "dedicated-hosts"],
  },
  {
    id: "saa-d4-013",
    section: "d4-cost-optimized",
    subtopic: "ec2-purchasing",
    type: "single",
    prompt:
      "You want to deploy a database on EC2 where the vendor license bills based on physical cores and underlying network socket visibility. Which EC2 Purchasing Option gives you visibility into them?",
    options: [
      { id: "a", text: "Spot Instances" },
      { id: "b", text: "On-Demand" },
      { id: "c", text: "Dedicated Hosts" },
      { id: "d", text: "Reserved Instances" },
    ],
    correct: ["c"],
    explanation:
      "Dedicated Hosts expose the physical sockets and cores of the underlying server, which is required for socket/core-based software licensing.",
    difficulty: "medium",
    services: ["ec2", "dedicated-hosts"],
  },
  {
    id: "saa-d4-014",
    section: "d4-cost-optimized",
    subtopic: "ec2-spot",
    type: "single",
    prompt: "Spot Fleet is a set of Spot Instances and optionally ……………",
    options: [
      { id: "a", text: "Reserved Instances" },
      { id: "b", text: "On-Demand Instances" },
      { id: "c", text: "Dedicated Hosts" },
      { id: "d", text: "Dedicated Instances" },
    ],
    correct: ["b"],
    explanation:
      "A Spot Fleet is a collection of Spot Instances and, optionally, On-Demand Instances, launched to meet a target capacity at the lowest cost.",
    difficulty: "medium",
    services: ["ec2", "spot"],
  },
  {
    id: "saa-d4-015",
    section: "d4-cost-optimized",
    subtopic: "ec2-hibernate",
    type: "single",
    prompt: "The following are true regarding EC2 Hibernate, EXCEPT:",
    options: [
      { id: "a", text: "EC2 Instance Root Volume must be an Instance Store volume" },
      { id: "b", text: "Supports On-Demand and Reserved Instances" },
      { id: "c", text: "EC2 Instance RAM must be less than 150 GB" },
      { id: "d", text: "EC2 Instance Root Volume type must be an EBS volume" },
    ],
    correct: ["a"],
    explanation:
      "For hibernation the root volume must be an encrypted EBS volume — not an instance store volume. The other statements are true.",
    difficulty: "hard",
    services: ["ec2"],
  },
  {
    id: "saa-d4-016",
    section: "d4-cost-optimized",
    subtopic: "s3-storage-classes",
    type: "single",
    prompt:
      "Data in Amazon S3 is accessed only a few times per month but must be retrieved immediately (milliseconds) when needed. Which storage class is the most cost-effective?",
    options: [
      { id: "a", text: "S3 Standard-IA (Infrequent Access)" },
      { id: "b", text: "S3 Standard" },
      { id: "c", text: "S3 Glacier Deep Archive" },
      { id: "d", text: "S3 Express One Zone" },
    ],
    correct: ["a"],
    explanation:
      "S3 Standard-IA offers lower storage cost with millisecond retrieval for infrequently accessed data (a per-GB retrieval fee applies). Glacier Deep Archive is far cheaper but has hours-long retrieval, unsuitable for immediate access.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-017",
    section: "d4-cost-optimized",
    type: "single",
    prompt:
      "A company wants the lowest compute cost across EC2, Fargate, and Lambda, with the flexibility to change instance families, sizes, and Regions, in exchange for a 1- or 3-year spend commitment. What should they choose?",
    options: [
      { id: "a", text: "Compute Savings Plans" },
      { id: "b", text: "Standard Reserved Instances" },
      { id: "c", text: "Spot Instances" },
      { id: "d", text: "On-Demand Instances" },
    ],
    correct: ["a"],
    explanation:
      "Compute Savings Plans give the broadest flexibility — any instance family, size, and Region, plus Fargate and Lambda — for a committed hourly spend. Standard RIs are cheaper but lock you to specific attributes.",
    difficulty: "medium",
    services: ["savings-plans"],
  },
  {
    id: "saa-d4-018",
    section: "d4-cost-optimized",
    subtopic: "cloudfront",
    type: "single",
    prompt:
      "A website serves the same large static assets to many global users directly from its origin, causing high data-transfer costs and latency. What change reduces cost and improves performance?",
    options: [
      { id: "a", text: "Serve the assets through Amazon CloudFront" },
      { id: "b", text: "Increase the EC2 instance size" },
      { id: "c", text: "Move the assets to a more expensive S3 storage class" },
      { id: "d", text: "Allocate additional Elastic IP addresses" },
    ],
    correct: ["a"],
    explanation:
      "CloudFront caches content at edge locations, so repeated requests are served from the edge — lowering origin data-transfer (egress) costs and improving latency for global users.",
    difficulty: "easy",
    services: ["cloudfront"],
  },
  {
    id: "saa-d4-019",
    section: "d4-cost-optimized",
    subtopic: "ec2-purchasing",
    type: "single",
    prompt: "What is the difference between a Dedicated Host and a Dedicated Instance?",
    options: [
      { id: "a", text: "A Dedicated Host gives visibility into and control of the physical server (sockets/cores) for BYOL; a Dedicated Instance runs on hardware dedicated to you but without that physical visibility" },
      { id: "b", text: "They are exactly the same thing" },
      { id: "c", text: "A Dedicated Instance is a cheaper form of Spot" },
      { id: "d", text: "A Dedicated Host is serverless" },
    ],
    correct: ["a"],
    explanation:
      "Dedicated Hosts expose the physical sockets/cores (useful for socket-based licensing), while Dedicated Instances simply guarantee dedicated hardware without that low-level visibility.",
    difficulty: "medium",
    services: ["ec2", "dedicated-hosts"],
  },
  {
    id: "saa-d4-020",
    section: "d4-cost-optimized",
    subtopic: "ec2-spot",
    type: "single",
    prompt: "What characterizes EC2 Spot Instances?",
    options: [
      { id: "a", text: "Spare capacity offered at a steep discount that AWS can reclaim with little notice" },
      { id: "b", text: "Capacity reserved for a 3-year term" },
      { id: "c", text: "Always-on, guaranteed capacity that is never interrupted" },
      { id: "d", text: "Instances that are completely free" },
    ],
    correct: ["a"],
    explanation:
      "Spot uses spare EC2 capacity at up to ~90% off, but AWS can reclaim it (with a short interruption notice) when it needs the capacity back.",
    difficulty: "easy",
    services: ["ec2", "spot"],
  },
  {
    id: "saa-d4-021",
    section: "d4-cost-optimized",
    subtopic: "ec2-spot",
    type: "single",
    prompt: "Which workload is the BEST fit for Spot Instances?",
    options: [
      { id: "a", text: "Fault-tolerant, flexible batch jobs that can be interrupted and resumed" },
      { id: "b", text: "A primary production database" },
      { id: "c", text: "A stateful session server with no failover" },
      { id: "d", text: "A single critical billing service" },
    ],
    correct: ["a"],
    explanation:
      "Spot suits interruptible, fault-tolerant work (batch processing, CI, big-data tasks). Critical or stateful single points of failure should not run on Spot.",
    difficulty: "easy",
    services: ["ec2", "spot"],
  },
  {
    id: "saa-d4-022",
    section: "d4-cost-optimized",
    subtopic: "ec2-spot",
    type: "single",
    prompt: "What is the purpose of a Spot Fleet?",
    options: [
      { id: "a", text: "To launch a target capacity using Spot (and optionally On-Demand) instances at the lowest possible price" },
      { id: "b", text: "To reserve capacity for one year" },
      { id: "c", text: "To create and manage a load balancer" },
      { id: "d", text: "To encrypt EBS volumes automatically" },
    ],
    correct: ["a"],
    explanation:
      "A Spot Fleet provisions a desired target capacity from Spot (optionally plus On-Demand) across instance pools to minimize cost while meeting capacity.",
    difficulty: "medium",
    services: ["ec2", "spot"],
  },
  {
    id: "saa-d4-023",
    section: "d4-cost-optimized",
    subtopic: "ec2-hibernate",
    type: "single",
    prompt: "What does EC2 Hibernate do?",
    options: [
      { id: "a", text: "Saves the in-memory (RAM) state to the EBS root volume so the instance resumes where it left off" },
      { id: "b", text: "Terminates the instance to save cost" },
      { id: "c", text: "Migrates the instance to another Region" },
      { id: "d", text: "Creates an AMI and deletes the instance" },
    ],
    correct: ["a"],
    explanation:
      "Hibernate writes RAM contents to the encrypted EBS root volume; on resume the OS and applications continue from that saved state.",
    difficulty: "medium",
    services: ["ec2"],
  },
  {
    id: "saa-d4-024",
    section: "d4-cost-optimized",
    subtopic: "ec2-hibernate",
    type: "single",
    prompt: "Why use EC2 Hibernate instead of a normal stop/start for some workloads?",
    options: [
      { id: "a", text: "It preserves RAM state for a faster resume (no full reboot or application reload)" },
      { id: "b", text: "It is always cheaper than stopping" },
      { id: "c", text: "It changes the instance type automatically" },
      { id: "d", text: "It removes the need for an AMI" },
    ],
    correct: ["a"],
    explanation:
      "Hibernate is useful for instances with long boot times or large in-memory caches — resuming restores RAM so the app is ready quickly.",
    difficulty: "medium",
    services: ["ec2"],
  },
  {
    id: "saa-d4-025",
    section: "d4-cost-optimized",
    subtopic: "ec2-hibernate",
    type: "single",
    prompt: "Which is a requirement to enable EC2 Hibernate?",
    options: [
      { id: "a", text: "The root volume must be an (encrypted) EBS volume with enough space to store the RAM contents" },
      { id: "b", text: "The root volume must be instance store" },
      { id: "c", text: "The instance RAM must exceed 150 GB" },
      { id: "d", text: "The instance must be a Spot Instance" },
    ],
    correct: ["a"],
    explanation:
      "Hibernation needs an encrypted EBS root volume large enough to hold RAM, and RAM must be under the supported limit. Instance store cannot be the root for hibernate.",
    difficulty: "medium",
    services: ["ec2", "ebs"],
  },
  {
    id: "saa-d4-026",
    section: "d4-cost-optimized",
    subtopic: "ec2-hibernate",
    type: "single",
    prompt: "While an EC2 instance is hibernated, what are you charged for?",
    options: [
      { id: "a", text: "No instance compute charges, but you still pay for EBS storage (and any Elastic IP)" },
      { id: "b", text: "Full On-Demand compute charges continue" },
      { id: "c", text: "Nothing at all is charged" },
      { id: "d", text: "Only data transfer charges" },
    ],
    correct: ["a"],
    explanation:
      "Like a stopped instance, a hibernated instance incurs no compute charges, but EBS volumes (storing the RAM state and data) and Elastic IPs still cost money.",
    difficulty: "medium",
    services: ["ec2", "ebs"],
  },
  {
    id: "saa-d4-027",
    section: "d4-cost-optimized",
    subtopic: "beanstalk",
    type: "single",
    prompt: "How much does AWS Elastic Beanstalk itself cost?",
    options: [
      { id: "a", text: "Beanstalk is free; you only pay for the underlying resources it provisions (EC2, ELB, RDS, etc.)" },
      { id: "b", text: "A flat monthly platform fee" },
      { id: "c", text: "A charge per deployment" },
      { id: "d", text: "A charge per request served" },
    ],
    correct: ["a"],
    explanation:
      "There is no additional charge for Beanstalk — you pay only for the AWS resources it creates and manages on your behalf.",
    difficulty: "medium",
    services: ["elastic-beanstalk"],
  },
  {
    id: "saa-d4-028",
    section: "d4-cost-optimized",
    subtopic: "s3-storage-classes",
    type: "single",
    prompt: "Which best describes S3 storage classes?",
    options: [
      { id: "a", text: "Tiers (Standard, Standard-IA, One Zone-IA, Glacier tiers, Intelligent-Tiering) that trade retrieval cost/latency for lower storage cost" },
      { id: "b", text: "Different encryption strengths" },
      { id: "c", text: "Different bucket Regions" },
      { id: "d", text: "Different IAM permission levels" },
    ],
    correct: ["a"],
    explanation:
      "Storage classes let you match cost to access pattern — frequently accessed (Standard) down to deep archive (Glacier Deep Archive), with Intelligent-Tiering automating moves.",
    difficulty: "easy",
    services: ["s3"],
  },
  {
    id: "saa-d4-029",
    section: "d4-cost-optimized",
    subtopic: "s3-storage-classes",
    type: "single",
    prompt: "When is S3 One Zone-IA appropriate?",
    options: [
      { id: "a", text: "Infrequently accessed data that can be recreated and doesn't need multi-AZ resilience (stored in one AZ, cheaper)" },
      { id: "b", text: "Critical data needing maximum durability across AZs" },
      { id: "c", text: "Frequently accessed hot data" },
      { id: "d", text: "Data that must be replicated across Regions immediately" },
    ],
    correct: ["a"],
    explanation:
      "One Zone-IA stores data in a single AZ at lower cost — fine for re-creatable, infrequently accessed data, but it loses data if that AZ is destroyed.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-030",
    section: "d4-cost-optimized",
    subtopic: "s3-storage-classes",
    type: "single",
    prompt:
      "Which S3 storage class is cheapest for long-term archives that are almost never accessed and can tolerate hours-long retrieval?",
    options: [
      { id: "a", text: "S3 Glacier Deep Archive" },
      { id: "b", text: "S3 Standard" },
      { id: "c", text: "S3 Standard-IA" },
      { id: "d", text: "S3 Express One Zone" },
    ],
    correct: ["a"],
    explanation:
      "Glacier Deep Archive is the lowest-cost class for rarely accessed data with the longest retrieval times (hours). Express One Zone is the opposite — ultra-low latency, higher cost.",
    difficulty: "medium",
    services: ["s3", "s3-glacier"],
  },
  {
    id: "saa-d4-031",
    section: "d4-cost-optimized",
    subtopic: "s3-lifecycle",
    type: "single",
    prompt: "What do S3 Lifecycle rules do?",
    options: [
      { id: "a", text: "Automatically transition objects between storage classes and/or expire (delete) them on a schedule" },
      { id: "b", text: "Encrypt objects at rest" },
      { id: "c", text: "Replicate objects across Regions" },
      { id: "d", text: "Serve objects as a static website" },
    ],
    correct: ["a"],
    explanation:
      "Lifecycle rules move objects to cheaper classes (transitions) and/or delete them (expiration) automatically based on age — matching cost to access pattern.",
    difficulty: "easy",
    services: ["s3"],
  },
  {
    id: "saa-d4-032",
    section: "d4-cost-optimized",
    subtopic: "s3-lifecycle",
    type: "single",
    prompt:
      "In a versioned bucket, how do you automatically delete old (noncurrent) object versions to save cost?",
    options: [
      { id: "a", text: "A lifecycle rule that expires noncurrent versions after a set number of days" },
      { id: "b", text: "Disable versioning entirely" },
      { id: "c", text: "Manually delete each old version" },
      { id: "d", text: "Enable Cross-Region Replication" },
    ],
    correct: ["a"],
    explanation:
      "Lifecycle rules can target noncurrent (older) versions for expiration, controlling the storage cost of versioned buckets.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-033",
    section: "d4-cost-optimized",
    subtopic: "s3-lifecycle",
    type: "single",
    prompt: "What does S3 Storage Class Analysis (S3 Analytics) help you do?",
    options: [
      { id: "a", text: "Analyze access patterns to recommend when to transition objects to Standard-IA" },
      { id: "b", text: "Encrypt objects automatically" },
      { id: "c", text: "Replicate buckets across Regions" },
      { id: "d", text: "Host a static website" },
    ],
    correct: ["a"],
    explanation:
      "S3 Analytics observes access patterns and suggests lifecycle transition timing (e.g., Standard → Standard-IA). It doesn't move data itself.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-034",
    section: "d4-cost-optimized",
    subtopic: "s3-lifecycle",
    type: "single",
    prompt:
      "When should you choose S3 Intelligent-Tiering instead of manual lifecycle transition rules?",
    options: [
      { id: "a", text: "When access patterns are unknown or changing and you want automatic tiering with no retrieval fees for the tier moves" },
      { id: "b", text: "When you know the access pattern precisely and it never changes" },
      { id: "c", text: "Only for static websites" },
      { id: "d", text: "Only to encrypt objects" },
    ],
    correct: ["a"],
    explanation:
      "Intelligent-Tiering automatically moves objects between access tiers based on usage (no retrieval fees for those moves) — best when patterns are unpredictable. Known patterns can use cheaper explicit lifecycle rules.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-035",
    section: "d4-cost-optimized",
    subtopic: "s3-operations",
    type: "single",
    prompt: "What does S3 Requester Pays do?",
    options: [
      { id: "a", text: "Shifts request and data-transfer costs to the requester instead of the bucket owner" },
      { id: "b", text: "Makes all downloads free" },
      { id: "c", text: "Encrypts every request" },
      { id: "d", text: "Blocks all public access" },
    ],
    correct: ["a"],
    explanation:
      "With Requester Pays, authenticated requesters pay for their requests and downloads — useful when sharing large datasets without bearing the transfer cost.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-036",
    section: "d4-cost-optimized",
    subtopic: "s3-operations",
    type: "single",
    prompt: "What is S3 Batch Operations used for?",
    options: [
      { id: "a", text: "Performing bulk actions (copy, tag, restore, invoke Lambda) across large numbers of existing objects" },
      { id: "b", text: "Real-time per-object event processing" },
      { id: "c", text: "Hosting a website" },
      { id: "d", text: "DNS routing" },
    ],
    correct: ["a"],
    explanation:
      "S3 Batch Operations runs a single operation across millions of objects from an inventory/manifest — e.g., bulk copy, re-tag, restore from Glacier, or invoke a Lambda.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-037",
    section: "d4-cost-optimized",
    subtopic: "s3-operations",
    type: "single",
    prompt: "What does S3 Storage Lens provide?",
    options: [
      { id: "a", text: "Organization-wide visibility into storage usage and activity, with metrics and cost-optimization recommendations" },
      { id: "b", text: "A content delivery network" },
      { id: "c", text: "Object-level encryption" },
      { id: "d", text: "A load balancer for S3" },
    ],
    correct: ["a"],
    explanation:
      "Storage Lens gives dashboards and metrics across accounts/buckets to understand usage and find cost-saving and data-protection opportunities.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-038",
    section: "d4-cost-optimized",
    subtopic: "s3-operations",
    type: "single",
    prompt:
      "How can you reduce storage cost from abandoned, incomplete multipart uploads?",
    options: [
      { id: "a", text: "Add a lifecycle rule that aborts incomplete multipart uploads after N days" },
      { id: "b", text: "Disable multipart uploads entirely" },
      { id: "c", text: "Enable versioning" },
      { id: "d", text: "Turn on Requester Pays" },
    ],
    correct: ["a"],
    explanation:
      "Incomplete multipart uploads still consume storage you pay for. A lifecycle rule to abort them after a few days cleans up that waste automatically.",
    difficulty: "medium",
    services: ["s3"],
  },
  {
    id: "saa-d4-039",
    section: "d4-cost-optimized",
    subtopic: "snow",
    type: "single",
    prompt: "What is the AWS Snow Family used for?",
    options: [
      { id: "a", text: "Physically migrating large amounts of data into/out of AWS using ruggedized devices when network transfer is too slow or costly" },
      { id: "b", text: "Real-time data streaming" },
      { id: "c", text: "Hosting a relational database" },
      { id: "d", text: "Serving cached content at the edge" },
    ],
    correct: ["a"],
    explanation:
      "Snow devices are shipped to you to move large datasets offline — useful when transferring over the internet would take too long or cost too much.",
    difficulty: "easy",
    services: ["snow-family"],
  },
  {
    id: "saa-d4-040",
    section: "d4-cost-optimized",
    subtopic: "snow",
    type: "single",
    prompt:
      "You must transfer 80 TB from a remote site with poor, slow internet into Amazon S3. What is most appropriate?",
    options: [
      { id: "a", text: "Ship the data using an AWS Snowball Edge device" },
      { id: "b", text: "Upload directly over the internet" },
      { id: "c", text: "Use only AWS DataSync over the slow link" },
      { id: "d", text: "Set up Direct Connect just for this one-time transfer" },
    ],
    correct: ["a"],
    explanation:
      "For large datasets over slow/unreliable links, Snowball Edge (offline shipping) is faster and cheaper than network transfer.",
    difficulty: "medium",
    services: ["snow-family"],
  },
  {
    id: "saa-d4-041",
    section: "d4-cost-optimized",
    subtopic: "snow",
    type: "single",
    prompt:
      "Which Snow device is intended for the largest (petabyte-to-exabyte) data-center migrations?",
    options: [
      { id: "a", text: "AWS Snowmobile" },
      { id: "b", text: "AWS Snowcone" },
      { id: "c", text: "A single AWS Snowball Edge" },
      { id: "d", text: "AWS Transfer Family" },
    ],
    correct: ["a"],
    explanation:
      "Snowmobile (a shipping container on a truck) moves up to ~100 PB per unit — for exabyte-scale migrations. Snowcone is the smallest device.",
    difficulty: "medium",
    services: ["snow-family"],
  },
  {
    id: "saa-d4-042",
    section: "d4-cost-optimized",
    subtopic: "snow",
    type: "single",
    prompt:
      "After importing data via Snowball into Amazon S3, how do you cheaply archive it for the long term?",
    options: [
      { id: "a", text: "Use an S3 lifecycle policy to transition it to Glacier / Glacier Deep Archive" },
      { id: "b", text: "Keep it all in S3 Standard indefinitely" },
      { id: "c", text: "Export it again via Snowball" },
      { id: "d", text: "Move it to an instance store volume" },
    ],
    correct: ["a"],
    explanation:
      "A common pattern (\"Snowball into Glacier\") imports to S3, then lifecycle rules transition objects to the cheapest archival tiers.",
    difficulty: "medium",
    services: ["snow-family", "s3-glacier"],
  },
  {
    id: "saa-d4-043",
    section: "d4-cost-optimized",
    subtopic: "snow",
    type: "single",
    prompt:
      "Besides moving data, what can AWS Snowball Edge do at remote/edge locations?",
    options: [
      { id: "a", text: "Run local compute (EC2 instances / Lambda) to process data before or while shipping it" },
      { id: "b", text: "Host a global CDN" },
      { id: "c", text: "Replace IAM for authentication" },
      { id: "d", text: "Provide managed DNS" },
    ],
    correct: ["a"],
    explanation:
      "Snowball Edge includes onboard compute, so you can pre-process or run edge workloads where connectivity is limited.",
    difficulty: "medium",
    services: ["snow-family"],
  },
  {
    id: "saa-d4-044",
    section: "d4-cost-optimized",
    subtopic: "hybrid-storage",
    type: "single",
    prompt:
      "Which service gives on-premises applications low-latency access to virtually unlimited cloud storage (File, Volume, or Tape Gateway), bridging on-prem and AWS?",
    options: [
      { id: "a", text: "AWS Storage Gateway" },
      { id: "b", text: "AWS DataSync" },
      { id: "c", text: "AWS Snowball" },
      { id: "d", text: "Amazon FSx" },
    ],
    correct: ["a"],
    explanation:
      "Storage Gateway is a hybrid service that exposes cloud-backed storage on-premises with local caching (File/Volume/Tape Gateway types).",
    difficulty: "medium",
    services: ["storage-gateway"],
  },
  {
    id: "saa-d4-045",
    section: "d4-cost-optimized",
    subtopic: "hybrid-storage",
    type: "single",
    prompt:
      "Which service automates and accelerates moving large amounts of data between on-premises (or other clouds) and AWS storage (S3, EFS, FSx) over the network, on a schedule?",
    options: [
      { id: "a", text: "AWS DataSync" },
      { id: "b", text: "AWS Storage Gateway" },
      { id: "c", text: "AWS Snowmobile" },
      { id: "d", text: "Amazon CloudFront" },
    ],
    correct: ["a"],
    explanation:
      "DataSync is a managed online transfer service for large, recurring data movement to/from AWS storage, with scheduling and integrity checks.",
    difficulty: "medium",
    services: ["datasync"],
  },
  {
    id: "saa-d4-046",
    section: "d4-cost-optimized",
    subtopic: "hybrid-storage",
    type: "single",
    prompt:
      "You need partners to upload files into Amazon S3/EFS using SFTP, FTPS, or FTP. Which service?",
    options: [
      { id: "a", text: "AWS Transfer Family" },
      { id: "b", text: "AWS DataSync" },
      { id: "c", text: "AWS Storage Gateway" },
      { id: "d", text: "AWS Snowball" },
    ],
    correct: ["a"],
    explanation:
      "AWS Transfer Family provides managed SFTP/FTPS/FTP endpoints that land files directly in S3 or EFS.",
    difficulty: "medium",
    services: ["transfer-family"],
  },
  {
    id: "saa-d4-047",
    section: "d4-cost-optimized",
    subtopic: "ecs-fargate",
    type: "single",
    prompt: "When should you choose AWS Fargate over the ECS EC2 launch type?",
    options: [
      { id: "a", text: "When you want to run containers without provisioning, patching, or scaling EC2 instances — serverless, paying per task's resources" },
      { id: "b", text: "When you need to manage the host OS yourself" },
      { id: "c", text: "When you need object storage" },
      { id: "d", text: "When you need DNS hosting" },
    ],
    correct: ["a"],
    explanation:
      "Fargate removes server management and bills per task vCPU/memory. The EC2 launch type can be cheaper at steady high utilization but requires you to manage the fleet.",
    difficulty: "medium",
    services: ["fargate", "ecs"],
  },
  {
    id: "saa-d4-048",
    section: "d4-cost-optimized",
    subtopic: "lambda",
    type: "single",
    prompt: "How are you billed for AWS Lambda?",
    options: [
      { id: "a", text: "Per request and per compute time (GB-seconds); you pay nothing while idle" },
      { id: "b", text: "A flat monthly fee regardless of usage" },
      { id: "c", text: "Per EC2 instance hour" },
      { id: "d", text: "Per gigabyte of data stored" },
    ],
    correct: ["a"],
    explanation:
      "Lambda charges for the number of requests and the compute duration × memory (GB-seconds). With no traffic, there's no charge — ideal for spiky or low-volume workloads.",
    difficulty: "easy",
    services: ["lambda"],
  },
  {
    id: "saa-d4-049",
    section: "d4-cost-optimized",
    subtopic: "vpc-fundamentals",
    type: "single",
    prompt:
      "Which network design choice helps reduce data-transfer costs between EC2 instances that communicate heavily?",
    options: [
      { id: "a", text: "Keep the instances in the same Availability Zone (traffic over private IPs within an AZ is free), since cross-AZ traffic incurs charges" },
      { id: "b", text: "Spread them across as many AZs and Regions as possible" },
      { id: "c", text: "Send all traffic over public IP addresses" },
      { id: "d", text: "Route all internal traffic through a NAT gateway" },
    ],
    correct: ["a"],
    explanation:
      "Traffic between instances in the same AZ over private IPs is free, while cross-AZ and cross-Region transfer is billed. For chatty workloads, co-locating in one AZ cuts cost (balanced against resilience needs).",
    difficulty: "medium",
    services: ["vpc", "ec2"],
  },
  {
    id: "saa-d4-050",
    section: "d4-cost-optimized",
    subtopic: "vpc-connectivity",
    type: "single",
    prompt:
      "Instances in a private subnet access Amazon S3 heavily through a NAT gateway, generating high NAT data-processing charges. How can you reduce cost?",
    options: [
      { id: "a", text: "Create an S3 gateway VPC endpoint so traffic to S3 bypasses the NAT gateway (gateway endpoints are free)" },
      { id: "b", text: "Add a second NAT gateway" },
      { id: "c", text: "Move the bucket to a public subnet" },
      { id: "d", text: "Switch the instances to public IPs" },
    ],
    correct: ["a"],
    explanation:
      "A gateway VPC endpoint for S3 routes traffic privately without a NAT gateway, eliminating NAT data-processing and per-GB charges for that traffic. Gateway endpoints have no hourly cost.",
    difficulty: "medium",
    services: ["vpc-endpoints", "s3", "nat-gateway"],
  },
  {
    id: "saa-d4-051",
    section: "d4-cost-optimized",
    subtopic: "hybrid-networking",
    type: "single",
    prompt:
      "A startup needs hybrid connectivity to AWS quickly and cheaply, accepting variable performance. Which option fits best on cost and speed-to-deploy?",
    options: [
      { id: "a", text: "A Site-to-Site VPN — low cost and quick to set up over the existing internet connection" },
      { id: "b", text: "AWS Direct Connect — provision a dedicated physical line (weeks of lead time, higher cost)" },
      { id: "c", text: "Two redundant Direct Connect connections" },
      { id: "d", text: "VPC peering to the on-premises network" },
    ],
    correct: ["a"],
    explanation:
      "A Site-to-Site VPN is inexpensive and deployable in minutes over the internet. Direct Connect costs more and takes weeks to provision — worth it for consistent performance, but overkill when cost and speed matter most.",
    difficulty: "medium",
    services: ["vpn", "direct-connect"],
  },
  {
    id: "saa-d4-052",
    section: "d4-cost-optimized",
    subtopic: "backup-transfer",
    type: "single",
    prompt:
      "A company must move 80 TB to AWS but has limited internet bandwidth that would take months to upload. What is the most practical, cost-effective option?",
    options: [
      { id: "a", text: "Order an AWS Snowball Edge device and ship the data offline to AWS" },
      { id: "b", text: "Upload directly over the existing internet connection" },
      { id: "c", text: "Use a Site-to-Site VPN and copy with scp" },
      { id: "d", text: "Email the files in batches" },
    ],
    correct: ["a"],
    explanation:
      "When network transfer would take too long (bandwidth-limited), the Snow Family ships physical devices for offline bulk transfer — faster and cheaper than saturating the link for months. DataSync is better when bandwidth is adequate.",
    difficulty: "medium",
    services: ["snowball", "snow-family"],
  },
  {
    id: "saa-d4-053",
    section: "d4-cost-optimized",
    subtopic: "operations-mgmt",
    type: "single",
    prompt:
      "Non-production EC2 instances only need to run during business hours. Which solution reduces cost by automatically stopping and starting them on a schedule?",
    options: [
      { id: "a", text: "Instance Scheduler on AWS (or an EventBridge schedule invoking Lambda/SSM to stop/start instances)" },
      { id: "b", text: "Buy Reserved Instances for 24/7 usage" },
      { id: "c", text: "Increase the instance size" },
      { id: "d", text: "Attach larger EBS volumes" },
    ],
    correct: ["a"],
    explanation:
      "Stopping instances when idle (e.g., nights/weekends for dev/test) avoids paying for compute you don't use. Instance Scheduler (or EventBridge + Lambda/SSM) automates the start/stop schedule.",
    difficulty: "medium",
    services: ["instance-scheduler", "ec2"],
  },
  {
    id: "saa-d4-054",
    section: "d4-cost-optimized",
    subtopic: "cost-management",
    type: "single",
    prompt: "What is AWS Cost Explorer used for?",
    options: [
      { id: "a", text: "Visualizing, analyzing, and forecasting AWS spend and usage over time, with filtering/grouping by service, tag, account, etc." },
      { id: "b", text: "Encrypting billing data" },
      { id: "c", text: "Running batch jobs" },
      { id: "d", text: "Hosting static websites" },
    ],
    correct: ["a"],
    explanation:
      "Cost Explorer provides interactive charts and forecasts of cost and usage, helping you understand spend trends and identify savings opportunities.",
    difficulty: "easy",
    services: ["cost-explorer"],
  },
  {
    id: "saa-d4-055",
    section: "d4-cost-optimized",
    subtopic: "cost-management",
    type: "single",
    prompt: "What does AWS Cost Anomaly Detection do?",
    options: [
      { id: "a", text: "Uses machine learning to detect unusual spending patterns and alert you to unexpected cost spikes" },
      { id: "b", text: "Sets hard spending limits that block new resources" },
      { id: "c", text: "Encrypts cost reports" },
      { id: "d", text: "Provisions infrastructure from templates" },
    ],
    correct: ["a"],
    explanation:
      "Cost Anomaly Detection applies ML to your spend to flag anomalies (e.g., a sudden spike) and notify you, so you can investigate unexpected charges quickly.",
    difficulty: "medium",
    services: ["cost-anomaly-detection"],
  },
  {
    id: "saa-d4-056",
    section: "d4-cost-optimized",
    subtopic: "cost-management",
    type: "single",
    prompt:
      "Match the cost tool to its job: forecasting/analyzing historical spend, automatically detecting unexpected spikes, and enforcing a budget threshold with alerts.",
    options: [
      { id: "a", text: "Cost Explorer = analyze/forecast; Cost Anomaly Detection = ML spike detection; AWS Budgets = threshold alerts" },
      { id: "b", text: "They all do the same thing" },
      { id: "c", text: "Budgets forecasts; Cost Explorer detects anomalies; Anomaly Detection sets limits" },
      { id: "d", text: "Cost Explorer enforces budgets; Budgets analyzes history" },
    ],
    correct: ["a"],
    explanation:
      "Cost Explorer analyzes/forecasts spend, Cost Anomaly Detection uses ML to surface unusual spikes, and AWS Budgets alerts (or acts) when you cross a defined threshold.",
    difficulty: "medium",
    services: ["cost-explorer", "cost-anomaly-detection", "budgets"],
  },
];
